// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rowops_4_1024
// target : apple-m-series
// launch : 1 threadgroups x 128 threads
// tg mem : 0 B tiles + 16400 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void rowops_4_1024(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_b [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[4100];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = (-INFINITY);
        if (o < 4u) for (uint j = lane; j < 1024u; j += 32u) s = max(s, float(float(p0_x[(uint)(0) * 1024u + (uint)(0) * 1u + ((o * 1024u + j))])));
        for (uint d = 16u; d > 0; d /= 2) s = max(s, simd_shuffle_down(s, d));
        if (o < 4u && lane % 32u == 0) scratch[0 + o * 1u + lane / 32u] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            float s = (-INFINITY);
            for (uint q = 0; q < 1u; ++q) s = max(s, scratch[0 + e * 1u + q]);
            v1[k] = float(s);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 1024u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 1024u]));
        }
    }
    float v3[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v3[k] = float(max(float(v2[k]), 0.0f) + precise::log(1.0f + precise::exp(-fabs(float(v2[k])))));
        }
    }
    float v5[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v5[k] = float(float(v3[k]) + float(float(p1_b[(uint)(0) * 1024u + (uint)(0) * 1u + ((e % 1024u))])));
        }
    }
    float v6[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v6[k] = float(precise::rsqrt(float(v5[k])));
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = 0.0f;
        if (o < 4u) for (uint j = lane; j < 1024u; j += 32u) s = s + float((scratch + 0)[o * 1024u + j]);
        for (uint d = 16u; d > 0; d /= 2) s = s + simd_shuffle_down(s, d);
        if (o < 4u && lane % 32u == 0) scratch[4096 + o * 1u + lane / 32u] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v7[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            float s = 0.0f;
            for (uint q = 0; q < 1u; ++q) s = s + scratch[4096 + e * 1u + q];
            v7[k] = float(s);
        }
    }
    float v8[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v8[k] = float(float(v6[k]) * float(v5[k]));
        }
    }
    float v9[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v9[k] = float(float(v8[k]) * 2.0f);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v10[32];
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            v10[k] = float(float(v9[k]) / float((scratch + 0)[e / 1024u]));
        }
    }
    for (uint k = 0; k < 32u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 4096u) {
            p2_y[(uint)(0) * 1024u + (uint)(0) * 1u + (e)] = float(float(v10[k]));
        }
    }
}
