// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rowops_300_7
// target : apple-m-series
// launch : 1 threadgroups x 128 threads
// tg mem : 0 B tiles + 8400 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void rowops_300_7(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_b [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[2100];
    float v1[3];
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            float s = (-INFINITY);
            for (uint j = 0; j < 7u; ++j) s = max(s, float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((e * 7u + j))])));
            v1[k] = float(s);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 7u]));
        }
    }
    float v3[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v3[k] = float(max(float(v2[k]), 0.0f) + precise::log(1.0f + precise::exp(-fabs(float(v2[k])))));
        }
    }
    float v5[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v5[k] = float(float(v3[k]) + float(float(p1_b[(uint)(0) * 7u + (uint)(0) * 1u + ((e % 7u))])));
        }
    }
    float v6[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v6[k] = float(precise::rsqrt(float(v5[k])));
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v7[3];
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            float s = 0.0f;
            for (uint j = 0; j < 7u; ++j) s = s + float((scratch + 0)[e * 7u + j]);
            v7[k] = float(s);
        }
    }
    float v8[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v8[k] = float(float(v6[k]) * float(v5[k]));
        }
    }
    float v9[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v9[k] = float(float(v8[k]) * 2.0f);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v10[17];
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            v10[k] = float(float(v9[k]) / float((scratch + 0)[e / 7u]));
        }
    }
    for (uint k = 0; k < 17u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 2100u) {
            p2_y[(uint)(0) * 7u + (uint)(0) * 1u + (e)] = float(float(v10[k]));
        }
    }
}
