// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rowops_300_7
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 8400 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void rowops_300_7(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_b,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[2100];
    float v1[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            float s = (-INFINITY);
            for (uint j = 0; j < 7u; ++j) s = max(s, float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((e * 7u + j))])));
            v1[k] = float(s);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    __syncthreads();
    float v2[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 7u]));
        }
    }
    float v3[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v3[k] = float(fmaxf(float(v2[k]), 0.0f) + logf(1.0f + expf(-fabsf(float(v2[k])))));
        }
    }
    float v5[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v5[k] = float(float(v3[k]) + float(float(p1_b[(uint)(0) * 7u + (uint)(0) * 1u + ((e % 7u))])));
        }
    }
    float v6[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v6[k] = float(rsqrtf(float(v5[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    __syncthreads();
    float v7[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            float s = 0.0f;
            for (uint j = 0; j < 7u; ++j) s = s + float((scratch + 0)[e * 7u + j]);
            v7[k] = float(s);
        }
    }
    float v8[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v8[k] = float(float(v6[k]) * float(v5[k]));
        }
    }
    float v9[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v9[k] = float(float(v8[k]) * 2.0f);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    __syncthreads();
    float v10[9];
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            v10[k] = float(float(v9[k]) / float((scratch + 0)[e / 7u]));
        }
    }
    for (uint k = 0; k < 9u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2100u) {
            p2_y[(uint)(0) * 7u + (uint)(0) * 1u + (e)] = float(float(v10[k]));
        }
    }
}
