// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_64_4096
// target : nvidia-ada
// launch : 1 threadgroups x 128 threads
// tg mem : 0 B tiles + 256 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void matvec_64_4096(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[64];
    __syncthreads();
    {
        const uint o = tid / 2u, lane = tid % 2u;
        float s = 0.0f;
        if (o < 64u) {
            const uint i = o / 64u, j = o % 64u;
            for (uint p0 = lane * 8u; p0 < 4096u; p0 += 16u) {
                for (uint u = 0; u < 8u; ++u) { const uint p = p0 + u; s += float(float(p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p))])) * float(float(p1_w[(uint)(0) * 4096u + (uint)(0) * 1u + ((j * 4096u + p))])); }
            }
        }
        for (uint d = 1u; d > 0; d /= 2) s += __shfl_down_sync(0xffffffffu, s, d);
        if (o < 64u && lane == 0) scratch[0 + o] = s;
    }
    __syncthreads();
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 64u) {
            v2[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 64u) {
            p2_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
