// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_1_8
// target : nvidia-ada
// launch : 1 threadgroups x 128 threads
// tg mem : 0 B tiles + 4 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void matvec_1_8(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[1];
    __syncthreads();
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = 0.0f;
        if (o < 1u) {
            const uint i = o / 1u, j = o % 1u;
            for (uint p = lane; p < 8u; p += 32u) s += float(float(p0_x[(uint)(0) * 8u + (uint)(0) * 1u + ((i * 8u + p))])) * float(float(p1_w[(uint)(0) * 8u + (uint)(0) * 1u + ((j * 8u + p))]));
        }
        for (uint d = 16u; d > 0; d /= 2) s += __shfl_down_sync(0xffffffffu, s, d);
        if (o < 1u && lane == 0) scratch[0 + o] = s;
    }
    __syncthreads();
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 1u) {
            v2[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 1u) {
            p2_y[(uint)(0) * 1u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
