// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_1_8
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 4 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void matvec_1_8(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[1];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = 0.0f;
        if (o < 1u) {
            const uint i = o / 1u, j = o % 1u;
            for (uint p = lane; p < 8u; p += 32u) s += float(float(p0_x[(uint)(0) * 8u + (uint)(0) * 1u + ((i * 8u + p))])) * float(float(p1_w[(uint)(0) * 8u + (uint)(0) * 1u + ((j * 8u + p))]));
        }
        for (uint d = 16u; d > 0; d /= 2) s += simd_shuffle_down(s, d);
        if (o < 1u && lane == 0) scratch[0 + o] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v2[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            p2_y[(uint)(0) * 1u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
