// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : softmax_4_64
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 1056 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void softmax_4_64(
    const float* __restrict__ p0_x,
    float* __restrict__ p1_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[264];
    __syncthreads();
    {
        const uint o = tid / 64u, lane = tid % 64u;
        float s = (-INFINITY);
        if (o < 4u) for (uint j = lane; j < 64u; j += 64u) s = max(s, float(float(p0_x[(uint)(0) * 64u + (uint)(0) * 1u + ((o * 64u + j))])));
        for (uint d = 16u; d > 0; d /= 2) s = max(s, __shfl_down_sync(0xffffffffu, s, d));
        if (o < 4u && lane % 32u == 0) scratch[0 + o * 2u + lane / 32u] = s;
    }
    __syncthreads();
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            float s = (-INFINITY);
            for (uint q = 0; q < 2u; ++q) s = max(s, scratch[0 + e * 2u + q]);
            v1[k] = float(s);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    __syncthreads();
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 64u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 64u]));
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v3[k] = float(expf(float(v2[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            scratch[0 + e] = float(v3[k]);
        }
    }
    __syncthreads();
    {
        const uint o = tid / 64u, lane = tid % 64u;
        float s = 0.0f;
        if (o < 4u) for (uint j = lane; j < 64u; j += 64u) s = s + float((scratch + 0)[o * 64u + j]);
        for (uint d = 16u; d > 0; d /= 2) s = s + __shfl_down_sync(0xffffffffu, s, d);
        if (o < 4u && lane % 32u == 0) scratch[256 + o * 2u + lane / 32u] = s;
    }
    __syncthreads();
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            float s = 0.0f;
            for (uint q = 0; q < 2u; ++q) s = s + scratch[256 + e * 2u + q];
            v4[k] = float(s);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v4[k]);
        }
    }
    __syncthreads();
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v5[k] = float(float(v3[k]) / float((scratch + 0)[e / 64u]));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            p1_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
