// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : silu_mul_16384_f32
// target : nvidia-ada
// launch : 64 threadgroups x 256 threads
// tg mem : 0 B tiles + 0 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void silu_mul_16384_f32(
    const float* __restrict__ p0_g,
    const float* __restrict__ p1_u,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v3[k] = float(1.0f / (1.0f + expf(-float(float(p0_g[((uint)(0) + (((e)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e)) / 1u % 256u)) * 1u])))));
        }
    }
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v4[k] = float(float(float(p0_g[((uint)(0) + (((e)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e)) / 1u % 256u)) * 1u])) * float(v3[k]));
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v5[k] = float(float(v4[k]) * float(float(p1_u[((uint)(0) + (((e / 1u)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e / 1u)) / 1u % 256u)) * 1u])));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            p2_y[((uint)(0) + ((e) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + ((e) / 1u % 256u)) * 1u] = float(float(v5[k]));
        }
    }
}
