// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : silu_mul_16384_f32
// target : apple-m-series
// launch : 64 threadgroups x 256 threads
// tg mem : 0 B tiles + 0 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void silu_mul_16384_f32(
    device const float* p0_g [[buffer(0)]],
    device const float* p1_u [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v3[k] = float(1.0f / (1.0f + precise::exp(-float(float(p0_g[((uint)(0) + (((e)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e)) / 1u % 256u)) * 1u])))));
        }
    }
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v4[k] = float(float(float(p0_g[((uint)(0) + (((e)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e)) / 1u % 256u)) * 1u])) * float(v3[k]));
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v5[k] = float(float(v4[k]) * float(float(p1_u[((uint)(0) + (((e / 1u)) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + (((e / 1u)) / 1u % 256u)) * 1u])));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            p2_y[((uint)(0) + ((e) / 256u % 1u)) * 16384u + ((uint)(0 + 256 * gid) + ((e) / 1u % 256u)) * 1u] = float(float(v5[k]));
        }
    }
}
