// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rowops_1_33
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 136 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void rowops_1_33(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_b,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[34];
    __syncthreads();
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = (-INFINITY);
        if (o < 1u) for (uint j = lane; j < 33u; j += 32u) s = max(s, float(float(p0_x[(uint)(0) * 33u + (uint)(0) * 1u + ((o * 33u + j))])));
        for (uint d = 16u; d > 0; d /= 2) s = max(s, __shfl_down_sync(0xffffffffu, s, d));
        if (o < 1u && lane % 32u == 0) scratch[0 + o * 1u + lane / 32u] = s;
    }
    __syncthreads();
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            float s = (-INFINITY);
            for (uint q = 0; q < 1u; ++q) s = max(s, scratch[0 + e * 1u + q]);
            v1[k] = float(s);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    __syncthreads();
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 33u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 33u]));
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v3[k] = float(fmaxf(float(v2[k]), 0.0f) + logf(1.0f + expf(-fabsf(float(v2[k])))));
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v5[k] = float(float(v3[k]) + float(float(p1_b[(uint)(0) * 33u + (uint)(0) * 1u + ((e / 1u))])));
        }
    }
    float v6[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v6[k] = float(rsqrtf(float(v5[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    __syncthreads();
    {
        const uint o = tid / 32u, lane = tid % 32u;
        float s = 0.0f;
        if (o < 1u) for (uint j = lane; j < 33u; j += 32u) s = s + float((scratch + 0)[o * 33u + j]);
        for (uint d = 16u; d > 0; d /= 2) s = s + __shfl_down_sync(0xffffffffu, s, d);
        if (o < 1u && lane % 32u == 0) scratch[33 + o * 1u + lane / 32u] = s;
    }
    __syncthreads();
    float v7[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            float s = 0.0f;
            for (uint q = 0; q < 1u; ++q) s = s + scratch[33 + e * 1u + q];
            v7[k] = float(s);
        }
    }
    float v8[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v8[k] = float(float(v6[k]) * float(v5[k]));
        }
    }
    float v9[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v9[k] = float(float(v8[k]) * 2.0f);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    __syncthreads();
    float v10[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            v10[k] = float(float(v9[k]) / float((scratch + 0)[e / 33u]));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 33u) {
            p2_y[(uint)(0) * 33u + (uint)(0) * 1u + (e)] = float(float(v10[k]));
        }
    }
}
