// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : softmax_3_7
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 96 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void softmax_3_7(
    device const float* p0_x [[buffer(0)]],
    device float* p1_y [[buffer(1)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[24];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 4u, lane = tid % 4u;
        float s = (-INFINITY);
        if (o < 3u) for (uint j = lane; j < 7u; j += 4u) s = max(s, float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((o * 7u + j))])));
        for (uint d = 2u; d > 0; d /= 2) s = max(s, simd_shuffle_down(s, d));
        if (o < 3u && lane % 32u == 0) scratch[0 + o * 1u + lane / 32u] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 3u) {
            float s = (-INFINITY);
            for (uint q = 0; q < 1u; ++q) s = max(s, scratch[0 + e * 1u + q]);
            v1[k] = float(s);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 3u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 21u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 7u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 7u]));
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 21u) {
            v3[k] = float(precise::exp(float(v2[k])));
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 21u) {
            scratch[0 + e] = float(v3[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 4u, lane = tid % 4u;
        float s = 0.0f;
        if (o < 3u) for (uint j = lane; j < 7u; j += 4u) s = s + float((scratch + 0)[o * 7u + j]);
        for (uint d = 2u; d > 0; d /= 2) s = s + simd_shuffle_down(s, d);
        if (o < 3u && lane % 32u == 0) scratch[21 + o * 1u + lane / 32u] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 3u) {
            float s = 0.0f;
            for (uint q = 0; q < 1u; ++q) s = s + scratch[21 + e * 1u + q];
            v4[k] = float(s);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 3u) {
            scratch[0 + e] = float(v4[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 21u) {
            v5[k] = float(float(v3[k]) / float((scratch + 0)[e / 7u]));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 21u) {
            p1_y[(uint)(0) * 7u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
