// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rmsnorm_792
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 32 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void rmsnorm_792(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[8];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 256u, lane = tid % 256u;
        float s = 0.0f;
        if (o < 1u) for (uint j = lane; j < 792u; j += 256u) s = s + float(float((float(float(p0_x[(uint)(0) * 792u + (uint)(0) * 1u + ((o * 792u + j))])) * float(float(p0_x[(uint)(0) * 792u + (uint)(0) * 1u + ((o * 792u + j))])))));
        for (uint d = 16u; d > 0; d /= 2) s = s + simd_shuffle_down(s, d);
        if (o < 1u && lane % 32u == 0) scratch[0 + o * 8u + lane / 32u] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            float s = 0.0f;
            for (uint q = 0; q < 8u; ++q) s = s + scratch[0 + e * 8u + q];
            v2[k] = float(s);
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v3[k] = float(float(v2[k]) * 0.0012626263f);
        }
    }
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v4[k] = float(1.919833e-11f);
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v5[k] = float(float(v3[k]) + float(v4[k]));
        }
    }
    float v6[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v6[k] = float(precise::rsqrt(float(v5[k])));
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v7[4];
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 792u) {
            v7[k] = float(float(float(p0_x[(uint)(0) * 792u + (uint)(0) * 1u + ((e))])) * float((scratch + 0)[e / 792u]));
        }
    }
    float v9[4];
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 792u) {
            v9[k] = float(float(v7[k]) * float(float(p1_w[(uint)(0) * 792u + (uint)(0) * 1u + ((e / 1u))])));
        }
    }
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 792u) {
            p2_y[(uint)(0) * 792u + (uint)(0) * 1u + (e)] = float(float(v9[k]));
        }
    }
}
