// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : stage_8_64_16
// target : apple-m-series
// launch : 1 threadgroups x 64 threads
// tg mem : 512 B tiles + 0 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void stage_8_64_16(
    device const float* p0_a [[buffer(0)]],
    device float* p1_y [[buffer(1)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float4 arena4[32];
    threadgroup uchar* arena = (threadgroup uchar*)arena4;
    float v0[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 64u + tid;
        if (e < 128u) {
            v0[k] = float(0.0f);
        }
    }
    float v2[2];
    for (uint k = 0; k < 2u; ++k) v2[k] = v0[k];
    for (uint v1 = 0u; v1 < 4u; ++v1) {
        threadgroup float* v4 = (threadgroup float*)(arena + 0);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 128u; e += 64u) {
            v4[e] = float(float(float(p0_a[((uint)(0) + (((e)) / 16u % 8u)) * 64u + ((uint)(0 + 16 * v1) + (((e)) / 1u % 16u)) * 1u])));
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v5[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 64u + tid;
            if (e < 128u) {
                v5[k] = float(float(v2[k]) + float(v4[e / 1u]));
            }
        }
        for (uint k = 0; k < 2u; ++k) v2[k] = v5[k];
    }
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 64u + tid;
        if (e < 128u) {
            p1_y[((uint)(0) + ((e) / 16u % 8u)) * 64u + ((uint)(0) + ((e) / 1u % 16u)) * 1u] = float(float(v2[k]));
        }
    }
}
