// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : stage_8_64_32
// target : nvidia-ada
// launch : 1 threadgroups x 64 threads
// tg mem : 1024 B tiles + 0 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void stage_8_64_32(
    const float* __restrict__ p0_a,
    float* __restrict__ p1_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float4 arena4[64];
    uchar* arena = (uchar*)arena4;
    float v0[4];
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 64u + tid;
        if (e < 256u) {
            v0[k] = float(0.0f);
        }
    }
    float v2[4];
    for (uint k = 0; k < 4u; ++k) v2[k] = v0[k];
    for (uint v1 = 0u; v1 < 2u; ++v1) {
        float* v4 = (float*)(arena + 0);
        __syncthreads();
        for (uint e = tid; e < 256u; e += 64u) {
            v4[e] = float(float(float(p0_a[((uint)(0) + (((e)) / 32u % 8u)) * 64u + ((uint)(0 + 32 * v1) + (((e)) / 1u % 32u)) * 1u])));
        }
        __syncthreads();
        float v5[4];
        for (uint k = 0; k < 4u; ++k) {
            const uint e = k * 64u + tid;
            if (e < 256u) {
                v5[k] = float(float(v2[k]) + float(v4[e / 1u]));
            }
        }
        for (uint k = 0; k < 4u; ++k) v2[k] = v5[k];
    }
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 64u + tid;
        if (e < 256u) {
            p1_y[((uint)(0) + ((e) / 32u % 8u)) * 64u + ((uint)(0) + ((e) / 1u % 32u)) * 1u] = float(float(v2[k]));
        }
    }
}
