// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_16_128_4096
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 8192 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void batch_fp4_16_128_4096(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[2048];
    __syncthreads();
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[16][16];
        for (uint rr = 0; rr < 16u; ++rr) for (uint i = 0; i < 16u; ++i) s[rr][i] = 0.0f;
        for (uint p0 = lane * 16u; p0 < 4096u; p0 += 512u) {
            float sgr[16], mgr[16];
            for (uint rr = 0; rr < 16u; ++rr) { const uint j = min(sgid * 16u + rr, 127u); const uint grp = j * 256u + p0 / 16u; sgr[rr] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 256u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[rr] = 0.0f; }
            for (uint u = 0; u < 16u; u += 2u) {
                const uint p = p0 + u;
                float xa[16][2];
                for (uint i = 0; i < 16u; ++i) xa[i][0] = float(float(p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p + 0u))]));
                for (uint i = 0; i < 16u; ++i) xa[i][1] = float(float(p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p + 1u))]));
                for (uint rr = 0; rr < 16u; ++rr) {
                    const uint j = min(sgid * 16u + rr, 127u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 2048u + (uint)(0) * 1u + ((j * 2048u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[rr]); const float w1 = (bq.y * sgr[rr]);
                    for (uint i = 0; i < 16u; ++i) s[rr][i] += xa[i][0] * w0 + xa[i][1] * w1;
                }
            }
        }
        for (uint rr = 0; rr < 16u; ++rr) for (uint i = 0; i < 16u; ++i) for (uint d = 16u; d > 0; d /= 2) s[rr][i] += __shfl_down_sync(0xffffffffu, s[rr][i], d);
        if (lane == 0) for (uint rr = 0; rr < 16u; ++rr) { const uint j = sgid * 16u + rr; if (j < 128u) for (uint i = 0; i < 16u; ++i) scratch[0 + i * 128u + j] = s[rr][i]; }
    }
    __syncthreads();
    float v5[8];
    for (uint k = 0; k < 8u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2048u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 8u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 2048u) {
            p4_y[(uint)(0) * 128u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
