// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : gemm_mma_128_128_64_64_64_32
// target : apple-m-series
// launch : 2 threadgroups x 128 threads
// tg mem : 8192 B tiles + 0 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

#include <metal_simdgroup_matrix>

kernel void gemm_mma_128_128_64_64_64_32(
    device const half* p0_a [[buffer(0)]],
    device const half* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x, gid2 = tgpos.y;
    threadgroup float4 arena4[512];
    threadgroup uchar* arena = (threadgroup uchar*)arena4;
    simdgroup_matrix<float, 8, 8> v2[4][4];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) v2[i][j] = simdgroup_matrix<float, 8, 8>(0.0f);
    simdgroup_matrix<float, 8, 8> v4[4][4];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) v4[i][j] = v2[i][j];
    for (uint v3 = 0u; v3 < 2u; ++v3) {
        threadgroup half* v5 = (threadgroup half*)(arena + 0);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 512u; e += 128u) {
            const uint r = e / 8u, c = (e % 8u) * 4u;
            *(threadgroup half4*)(&v5[r * 32u + c]) = *(const device half4 *)(&p0_a[((uint)(0 + 64 * gid) + (((r * 32u + c)) / 32u % 64u)) * 64u + ((uint)(0 + 32 * v3) + (((r * 32u + c)) / 1u % 32u)) * 1u]);
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        threadgroup half* v6 = (threadgroup half*)(arena + 4096);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 512u; e += 128u) {
            const uint r = e / 8u, c = (e % 8u) * 4u;
            *(threadgroup half4*)(&v6[r * 32u + c]) = *(const device half4 *)(&p1_w[((uint)(0 + 64 * gid2) + (((r * 32u + c)) / 32u % 64u)) * 64u + ((uint)(0 + 32 * v3) + (((r * 32u + c)) / 1u % 32u)) * 1u]);
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            simdgroup_matrix<half, 8, 8> fa[4], fb[4];
            for (uint kk = 0; kk < 32u; kk += 8u) {
                for (uint i = 0; i < 4u; ++i) simdgroup_load(fa[i], v5 + ((tid / 64u) * 32u + i * 8u) * 32u + kk, 32u);
                for (uint j = 0; j < 4u; ++j) simdgroup_load(fb[j], v6 + ((tid / 32u % 2u) * 32u + j * 8u) * 32u + kk, 32u, ulong2(0, 0), true);
                for (uint i = 0; i < 4u; ++i)
                    for (uint j = 0; j < 4u; ++j) simdgroup_multiply_accumulate(v4[i][j], fa[i], fb[j], v4[i][j]);
            }
        }
    }
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) simdgroup_store(v4[i][j], &p2_y[((uint)(0 + 64 * gid) + ((((tid / 64u) * 32u + i * 8u) * 64u + (tid / 32u % 2u) * 32u + j * 8u) / 64u % 64u)) * 128u + ((uint)(0 + 64 * gid2) + ((((tid / 64u) * 32u + i * 8u) * 64u + (tid / 32u % 2u) * 32u + j * 8u) / 1u % 64u)) * 1u], 128u);
}
