// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : gemm_mma_128_128_64_128_128_64
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 36864 B tiles + 0 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

#include <mma.h>

extern "C" __global__ void gemm_mma_128_128_64_128_128_64(
    const __half* __restrict__ p0_a,
    const __half* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x, gid2 = blockIdx.y;
    __shared__ __align__(32) float4 arena4[2304];
    uchar* arena = (uchar*)arena4;
    nvcuda::wmma::fragment<nvcuda::wmma::accumulator, 16, 16, 16, float> v2[4][2];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) nvcuda::wmma::fill_fragment(v2[i][j], 0.0f);
    nvcuda::wmma::fragment<nvcuda::wmma::accumulator, 16, 16, 16, float> v4[4][2];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) v4[i][j] = v2[i][j];
    for (uint v3 = 0u; v3 < 1u; ++v3) {
        __half* v5 = (__half*)(arena + 0);
        __syncthreads();
        for (uint e = tid; e < 1024u; e += 256u) {
            const uint r = e / 8u, c = (e % 8u) * 8u;
            *reinterpret_cast<uint4*>(&v5[r * 72u + c]) = *reinterpret_cast<const uint4*>(&p0_a[(uint)(0 + 128 * gid) * 64u + (uint)(0 + 64 * v3) * 1u + ((r * 64u + c))]);
        }
        __syncthreads();
        __half* v6 = (__half*)(arena + 18432);
        __syncthreads();
        for (uint e = tid; e < 1024u; e += 256u) {
            const uint r = e / 8u, c = (e % 8u) * 8u;
            *reinterpret_cast<uint4*>(&v6[r * 72u + c]) = *reinterpret_cast<const uint4*>(&p1_w[(uint)(0 + 128 * gid2) * 64u + (uint)(0 + 64 * v3) * 1u + ((r * 64u + c))]);
        }
        __syncthreads();
        {
            nvcuda::wmma::fragment<nvcuda::wmma::matrix_a, 16, 16, 16, __half, nvcuda::wmma::row_major> fa[4];
            nvcuda::wmma::fragment<nvcuda::wmma::matrix_b, 16, 16, 16, __half, nvcuda::wmma::col_major> fb[2];
            for (uint kk = 0; kk < 64u; kk += 16u) {
                for (uint i = 0; i < 4u; ++i) nvcuda::wmma::load_matrix_sync(fa[i], v5 + ((tid / 128u) * 64u + i * 16u) * 72u + kk, 72u);
                for (uint j = 0; j < 2u; ++j) nvcuda::wmma::load_matrix_sync(fb[j], v6 + ((tid / 32u % 4u) * 32u + j * 16u) * 72u + kk, 72u);
                for (uint i = 0; i < 4u; ++i)
                    for (uint j = 0; j < 2u; ++j) nvcuda::wmma::mma_sync(v4[i][j], fa[i], fb[j], v4[i][j]);
            }
        }
    }
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) nvcuda::wmma::store_matrix_sync(&p2_y[(uint)(0 + 128 * gid) * 128u + (uint)(0 + 128 * gid2) * 1u + (((tid / 128u) * 64u + i * 16u) * 128u + (tid / 32u % 4u) * 32u + j * 16u)], v4[i][j], 128u, nvcuda::wmma::mem_row_major);
}
