// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_fp4_32_48
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 128 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void matvec_fp4_32_48(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[32];
    __syncthreads();
    {
        const uint o = tid / 8u, lane = tid % 8u;
        float s = 0.0f;
        if (o < 32u) {
            const uint i = o / 32u, j = o % 32u;
            const float rs = float(float(p3_wg[(uint)(0) * 1u + ((j))]));
            for (uint p0 = lane * 2u; p0 < 48u; p0 += 16u) {
                const uint grp = j * 3u + p0 / 16u;
                const float sg = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 3u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * rs;
                float run = 0.0f;
                for (uint u = 0; u < 2u; u += 2u) { const uint p = p0 + u; const uint bq = (uint)(uchar)(char(p1_wq[(uint)(0) * 24u + (uint)(0) * 1u + ((j * 24u + p0 / 2u + u / 2u))])); const float2 w = fp4_pair(bq); run += float(float(p0_x[(uint)(0) * 48u + (uint)(0) * 1u + ((i * 48u + p))])) * w.x + float(float(p0_x[(uint)(0) * 48u + (uint)(0) * 1u + ((i * 48u + p + 1u))])) * w.y; }
                s += run * (sg * 16384.0f);
            }
        }
        for (uint d = 4u; d > 0; d /= 2) s += __shfl_down_sync(0xffffffffu, s, d);
        if (o < 32u && lane == 0) scratch[0 + o] = s;
    }
    __syncthreads();
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 32u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 32u) {
            p4_y[(uint)(0) * 32u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
