// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_3_40_96
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 480 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void batch_fp4_3_40_96(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[120];
    const float fp4_lane = FP4_V[tid & 15u];
    __syncthreads();
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[5][3];
        s[0][0] = 0.0f; s[0][1] = 0.0f; s[0][2] = 0.0f;
        s[1][0] = 0.0f; s[1][1] = 0.0f; s[1][2] = 0.0f;
        s[2][0] = 0.0f; s[2][1] = 0.0f; s[2][2] = 0.0f;
        s[3][0] = 0.0f; s[3][1] = 0.0f; s[3][2] = 0.0f;
        s[4][0] = 0.0f; s[4][1] = 0.0f; s[4][2] = 0.0f;
        for (uint p0 = lane * 1u; p0 < 96u; p0 += 32u) {
            for (uint u = 0; u < 1u; u += 1u) {
                const uint p = p0 + u;
                float xa[3][1];
                xa[0][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 0u))]));
                xa[1][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 96u))]));
                xa[2][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 192u))]));
                {
                    const uint j = min(sgid * 5u + 0u, 39u);
                    const float w0 = float((__shfl_sync(0xffffffffu, fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[0][0] += xa[0][0] * w0;
                    s[0][1] += xa[1][0] * w0;
                    s[0][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 1u, 39u);
                    const float w0 = float((__shfl_sync(0xffffffffu, fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[1][0] += xa[0][0] * w0;
                    s[1][1] += xa[1][0] * w0;
                    s[1][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 2u, 39u);
                    const float w0 = float((__shfl_sync(0xffffffffu, fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[2][0] += xa[0][0] * w0;
                    s[2][1] += xa[1][0] * w0;
                    s[2][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 3u, 39u);
                    const float w0 = float((__shfl_sync(0xffffffffu, fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[3][0] += xa[0][0] * w0;
                    s[3][1] += xa[1][0] * w0;
                    s[3][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 4u, 39u);
                    const float w0 = float((__shfl_sync(0xffffffffu, fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[4][0] += xa[0][0] * w0;
                    s[4][1] += xa[1][0] * w0;
                    s[4][2] += xa[2][0] * w0;
                }
            }
        }
        for (uint d = 16u; d > 0; d /= 2) s[0][0] += __shfl_down_sync(0xffffffffu, s[0][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][1] += __shfl_down_sync(0xffffffffu, s[0][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][2] += __shfl_down_sync(0xffffffffu, s[0][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][0] += __shfl_down_sync(0xffffffffu, s[1][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][1] += __shfl_down_sync(0xffffffffu, s[1][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][2] += __shfl_down_sync(0xffffffffu, s[1][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][0] += __shfl_down_sync(0xffffffffu, s[2][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][1] += __shfl_down_sync(0xffffffffu, s[2][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][2] += __shfl_down_sync(0xffffffffu, s[2][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][0] += __shfl_down_sync(0xffffffffu, s[3][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][1] += __shfl_down_sync(0xffffffffu, s[3][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][2] += __shfl_down_sync(0xffffffffu, s[3][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][0] += __shfl_down_sync(0xffffffffu, s[4][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][1] += __shfl_down_sync(0xffffffffu, s[4][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][2] += __shfl_down_sync(0xffffffffu, s[4][2], d);
        if (lane == 0) {
            { const uint j = sgid * 5u + 0u; if (j < 40u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 40u + j] = s[0][1]; scratch[0 + 80u + j] = s[0][2]; } }
            { const uint j = sgid * 5u + 1u; if (j < 40u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 40u + j] = s[1][1]; scratch[0 + 80u + j] = s[1][2]; } }
            { const uint j = sgid * 5u + 2u; if (j < 40u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 40u + j] = s[2][1]; scratch[0 + 80u + j] = s[2][2]; } }
            { const uint j = sgid * 5u + 3u; if (j < 40u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 40u + j] = s[3][1]; scratch[0 + 80u + j] = s[3][2]; } }
            { const uint j = sgid * 5u + 4u; if (j < 40u) { scratch[0 + 0u + j] = s[4][0]; scratch[0 + 40u + j] = s[4][1]; scratch[0 + 80u + j] = s[4][2]; } }
        }
    }
    __syncthreads();
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 120u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 120u) {
            p4_y[(uint)(0) * 40u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
