// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_3_40_96
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 480 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

constant float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
inline float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    return float2(as_type<half2>(((w & 0x00070007u) << 9u)
                               | ((w & 0x00080008u) << 12u)));
}
inline float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const uint bits = select(((e + 120u) << 23u) | (m << 20u),
                             as_type<uint>(float(m) * 0.001953125f), e == 0u);
    return as_type<float>(bits | ((b & 0x80u) << 24u));
}

kernel void batch_fp4_3_40_96(
    device const float* p0_x [[buffer(0)]],
    device const char* p1_wq [[buffer(1)]],
    device const char* p2_ws [[buffer(2)]],
    device const float* p3_wg [[buffer(3)]],
    device float* p4_y [[buffer(4)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[120];
    const float fp4_lane = FP4_V[tid & 15u];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[5][3];
        s[0][0] = 0.0f; s[0][1] = 0.0f; s[0][2] = 0.0f;
        s[1][0] = 0.0f; s[1][1] = 0.0f; s[1][2] = 0.0f;
        s[2][0] = 0.0f; s[2][1] = 0.0f; s[2][2] = 0.0f;
        s[3][0] = 0.0f; s[3][1] = 0.0f; s[3][2] = 0.0f;
        s[4][0] = 0.0f; s[4][1] = 0.0f; s[4][2] = 0.0f;
        for (uint p0 = lane * 1u; p0 < 96u; p0 += 32u) {
            for (uint u = 0; u < 1u; u += 1u) {
                const uint p = p0 + u;
                float xa[3][1];
                xa[0][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 0u))]));
                xa[1][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 96u))]));
                xa[2][0] = float(float(p0_x[(uint)(0) * 96u + (uint)(0) * 1u + ((p + 192u))]));
                {
                    const uint j = min(sgid * 5u + 0u, 39u);
                    const float w0 = float((simd_shuffle(fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[0][0] += xa[0][0] * w0;
                    s[0][1] += xa[1][0] * w0;
                    s[0][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 1u, 39u);
                    const float w0 = float((simd_shuffle(fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[1][0] += xa[0][0] * w0;
                    s[1][1] += xa[1][0] * w0;
                    s[1][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 2u, 39u);
                    const float w0 = float((simd_shuffle(fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[2][0] += xa[0][0] * w0;
                    s[2][1] += xa[1][0] * w0;
                    s[2][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 3u, 39u);
                    const float w0 = float((simd_shuffle(fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[3][0] += xa[0][0] * w0;
                    s[3][1] += xa[1][0] * w0;
                    s[3][2] += xa[2][0] * w0;
                }
                {
                    const uint j = min(sgid * 5u + 4u, 39u);
                    const float w0 = float((simd_shuffle(fp4_lane, ((uint)(uchar)(char(p1_wq[(uint)(0) * 48u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 48u + ((j * 96u + p) % 96u) / 2u))])) >> (((j * 96u + p) & 1u) * 4u)) & 0xFu) * fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 6u + (uint)(0) * 1u + ((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((((((j * 96u + p) / 96u) * 6u + ((j * 96u + p) % 96u) / 16u)) / 6u))]))));
                    s[4][0] += xa[0][0] * w0;
                    s[4][1] += xa[1][0] * w0;
                    s[4][2] += xa[2][0] * w0;
                }
            }
        }
        for (uint d = 16u; d > 0; d /= 2) s[0][0] += simd_shuffle_down(s[0][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][1] += simd_shuffle_down(s[0][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][2] += simd_shuffle_down(s[0][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][0] += simd_shuffle_down(s[1][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][1] += simd_shuffle_down(s[1][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][2] += simd_shuffle_down(s[1][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][0] += simd_shuffle_down(s[2][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][1] += simd_shuffle_down(s[2][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][2] += simd_shuffle_down(s[2][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][0] += simd_shuffle_down(s[3][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][1] += simd_shuffle_down(s[3][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][2] += simd_shuffle_down(s[3][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][0] += simd_shuffle_down(s[4][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][1] += simd_shuffle_down(s[4][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][2] += simd_shuffle_down(s[4][2], d);
        if (lane == 0) {
            { const uint j = sgid * 5u + 0u; if (j < 40u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 40u + j] = s[0][1]; scratch[0 + 80u + j] = s[0][2]; } }
            { const uint j = sgid * 5u + 1u; if (j < 40u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 40u + j] = s[1][1]; scratch[0 + 80u + j] = s[1][2]; } }
            { const uint j = sgid * 5u + 2u; if (j < 40u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 40u + j] = s[2][1]; scratch[0 + 80u + j] = s[2][2]; } }
            { const uint j = sgid * 5u + 3u; if (j < 40u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 40u + j] = s[3][1]; scratch[0 + 80u + j] = s[3][2]; } }
            { const uint j = sgid * 5u + 4u; if (j < 40u) { scratch[0 + 0u + j] = s[4][0]; scratch[0 + 40u + j] = s[4][1]; scratch[0 + 80u + j] = s[4][2]; } }
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 120u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 120u) {
            p4_y[(uint)(0) * 40u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
