// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rmsnorm_17
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 4 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void rmsnorm_17(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[1];
    __syncthreads();
    {
        const uint o = tid / 16u, lane = tid % 16u;
        float s = 0.0f;
        if (o < 1u) for (uint j = lane; j < 17u; j += 16u) s = s + float(float((float(float(p0_x[(uint)(0) * 17u + (uint)(0) * 1u + ((o * 17u + j))])) * float(float(p0_x[(uint)(0) * 17u + (uint)(0) * 1u + ((o * 17u + j))])))));
        for (uint d = 8u; d > 0; d /= 2) s = s + __shfl_down_sync(0xffffffffu, s, d);
        if (o < 1u && lane % 32u == 0) scratch[0 + o * 1u + lane / 32u] = s;
    }
    __syncthreads();
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            float s = 0.0f;
            for (uint q = 0; q < 1u; ++q) s = s + scratch[0 + e * 1u + q];
            v2[k] = float(s);
        }
    }
    float v3[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v3[k] = float(float(v2[k]) * 0.05882353f);
        }
    }
    float v4[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v4[k] = float(1e-5f);
        }
    }
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v5[k] = float(float(v3[k]) + float(v4[k]));
        }
    }
    float v6[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            v6[k] = float(rsqrtf(float(v5[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1u) {
            scratch[0 + e] = float(v6[k]);
        }
    }
    __syncthreads();
    float v7[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 17u) {
            v7[k] = float(float(float(p0_x[(uint)(0) * 17u + (uint)(0) * 1u + ((e))])) * float((scratch + 0)[e / 17u]));
        }
    }
    float v9[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 17u) {
            v9[k] = float(float(v7[k]) * float(float(p1_w[(uint)(0) * 17u + (uint)(0) * 1u + ((e / 1u))])));
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 17u) {
            p2_y[(uint)(0) * 17u + (uint)(0) * 1u + (e)] = float(float(v9[k]));
        }
    }
}
