// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : rowops_4_1024
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 16416 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void rowops_4_1024(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_b,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[4104];
    __syncthreads();
    {
        const uint o = tid / 64u, lane = tid % 64u;
        float s = (-INFINITY);
        if (o < 4u) for (uint j = lane; j < 1024u; j += 64u) s = max(s, float(float(p0_x[(uint)(0) * 1024u + (uint)(0) * 1u + ((o * 1024u + j))])));
        for (uint d = 16u; d > 0; d /= 2) s = max(s, __shfl_down_sync(0xffffffffu, s, d));
        if (o < 4u && lane % 32u == 0) scratch[0 + o * 2u + lane / 32u] = s;
    }
    __syncthreads();
    float v1[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            float s = (-INFINITY);
            for (uint q = 0; q < 2u; ++q) s = max(s, scratch[0 + e * 2u + q]);
            v1[k] = float(s);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v1[k]);
        }
    }
    __syncthreads();
    float v2[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v2[k] = float(float(float(p0_x[(uint)(0) * 1024u + (uint)(0) * 1u + ((e))])) - float((scratch + 0)[e / 1024u]));
        }
    }
    float v3[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v3[k] = float(fmaxf(float(v2[k]), 0.0f) + logf(1.0f + expf(-fabsf(float(v2[k])))));
        }
    }
    float v5[4];
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1024u) {
            v5[k] = float(fmaxf(float(float(p1_b[(uint)(0) * 1024u + (uint)(0) * 1u + ((e))])), 0.0f) + logf(1.0f + expf(-fabsf(float(float(p1_b[(uint)(0) * 1024u + (uint)(0) * 1u + ((e))]))))));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 4u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 1024u) {
            scratch[0 + e] = float(v5[k]);
        }
    }
    __syncthreads();
    float v6[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v6[k] = float(float(v3[k]) + float((scratch + 0)[e % 1024u]));
        }
    }
    float v7[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v7[k] = float(rsqrtf(float(v6[k])));
        }
    }
    __syncthreads();
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            scratch[0 + e] = float(v7[k]);
        }
    }
    __syncthreads();
    {
        const uint o = tid / 64u, lane = tid % 64u;
        float s = 0.0f;
        if (o < 4u) for (uint j = lane; j < 1024u; j += 64u) s = s + float((scratch + 0)[o * 1024u + j]);
        for (uint d = 16u; d > 0; d /= 2) s = s + __shfl_down_sync(0xffffffffu, s, d);
        if (o < 4u && lane % 32u == 0) scratch[4096 + o * 2u + lane / 32u] = s;
    }
    __syncthreads();
    float v8[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            float s = 0.0f;
            for (uint q = 0; q < 2u; ++q) s = s + scratch[4096 + e * 2u + q];
            v8[k] = float(s);
        }
    }
    float v9[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v9[k] = float(float(v7[k]) * float(v6[k]));
        }
    }
    float v10[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v10[k] = float(float(v9[k]) * 2.0f);
        }
    }
    __syncthreads();
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4u) {
            scratch[0 + e] = float(v8[k]);
        }
    }
    __syncthreads();
    float v11[16];
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            v11[k] = float(float(v10[k]) / float((scratch + 0)[e / 1024u]));
        }
    }
    for (uint k = 0; k < 16u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 4096u) {
            p2_y[(uint)(0) * 1024u + (uint)(0) * 1u + (e)] = float(float(v11[k]));
        }
    }
}
