// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_4_64_512
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 1024 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

constant float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
inline float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    return float2(as_type<half2>(((w & 0x00070007u) << 9u)
                               | ((w & 0x00080008u) << 12u)));
}
inline float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const uint bits = select(((e + 120u) << 23u) | (m << 20u),
                             as_type<uint>(float(m) * 0.001953125f), e == 0u);
    return as_type<float>(bits | ((b & 0x80u) << 24u));
}

kernel void batch_fp4_4_64_512(
    device const float* p0_x [[buffer(0)]],
    device const char* p1_wq [[buffer(1)]],
    device const char* p2_ws [[buffer(2)]],
    device const float* p3_wg [[buffer(3)]],
    device float* p4_y [[buffer(4)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[256];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[8][4];
        s[0][0] = 0.0f; s[0][1] = 0.0f; s[0][2] = 0.0f; s[0][3] = 0.0f;
        s[1][0] = 0.0f; s[1][1] = 0.0f; s[1][2] = 0.0f; s[1][3] = 0.0f;
        s[2][0] = 0.0f; s[2][1] = 0.0f; s[2][2] = 0.0f; s[2][3] = 0.0f;
        s[3][0] = 0.0f; s[3][1] = 0.0f; s[3][2] = 0.0f; s[3][3] = 0.0f;
        s[4][0] = 0.0f; s[4][1] = 0.0f; s[4][2] = 0.0f; s[4][3] = 0.0f;
        s[5][0] = 0.0f; s[5][1] = 0.0f; s[5][2] = 0.0f; s[5][3] = 0.0f;
        s[6][0] = 0.0f; s[6][1] = 0.0f; s[6][2] = 0.0f; s[6][3] = 0.0f;
        s[7][0] = 0.0f; s[7][1] = 0.0f; s[7][2] = 0.0f; s[7][3] = 0.0f;
        for (uint p0 = lane * 16u; p0 < 512u; p0 += 512u) {
            float sgr[8], mgr[8];
            { const uint j = min(sgid * 8u + 0u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[0] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[0] = 0.0f; }
            { const uint j = min(sgid * 8u + 1u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[1] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[1] = 0.0f; }
            { const uint j = min(sgid * 8u + 2u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[2] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[2] = 0.0f; }
            { const uint j = min(sgid * 8u + 3u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[3] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[3] = 0.0f; }
            { const uint j = min(sgid * 8u + 4u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[4] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[4] = 0.0f; }
            { const uint j = min(sgid * 8u + 5u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[5] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[5] = 0.0f; }
            { const uint j = min(sgid * 8u + 6u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[6] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[6] = 0.0f; }
            { const uint j = min(sgid * 8u + 7u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[7] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[7] = 0.0f; }
            for (uint u = 0; u < 16u; u += 2u) {
                const uint p = p0 + u;
                float xa[4][2];
                xa[0][0] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 0u))]));
                xa[1][0] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 512u))]));
                xa[2][0] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 1024u))]));
                xa[3][0] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 1536u))]));
                xa[0][1] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 1u))]));
                xa[1][1] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 513u))]));
                xa[2][1] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 1025u))]));
                xa[3][1] = float(float(p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((p + 1537u))]));
                {
                    const uint j = min(sgid * 8u + 0u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[0]); const float w1 = (bq.y * sgr[0]);
                    s[0][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[0][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[0][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[0][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 1u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[1]); const float w1 = (bq.y * sgr[1]);
                    s[1][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[1][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[1][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[1][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 2u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[2]); const float w1 = (bq.y * sgr[2]);
                    s[2][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[2][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[2][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[2][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 3u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[3]); const float w1 = (bq.y * sgr[3]);
                    s[3][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[3][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[3][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[3][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 4u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[4]); const float w1 = (bq.y * sgr[4]);
                    s[4][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[4][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[4][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[4][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 5u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[5]); const float w1 = (bq.y * sgr[5]);
                    s[5][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[5][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[5][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[5][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 6u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[6]); const float w1 = (bq.y * sgr[6]);
                    s[6][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[6][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[6][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[6][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
                {
                    const uint j = min(sgid * 8u + 7u, 63u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[7]); const float w1 = (bq.y * sgr[7]);
                    s[7][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[7][1] += xa[1][0] * w0 + xa[1][1] * w1;
                    s[7][2] += xa[2][0] * w0 + xa[2][1] * w1;
                    s[7][3] += xa[3][0] * w0 + xa[3][1] * w1;
                }
            }
        }
        for (uint d = 16u; d > 0; d /= 2) s[0][0] += simd_shuffle_down(s[0][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][1] += simd_shuffle_down(s[0][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][2] += simd_shuffle_down(s[0][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][3] += simd_shuffle_down(s[0][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][0] += simd_shuffle_down(s[1][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][1] += simd_shuffle_down(s[1][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][2] += simd_shuffle_down(s[1][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][3] += simd_shuffle_down(s[1][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][0] += simd_shuffle_down(s[2][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][1] += simd_shuffle_down(s[2][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][2] += simd_shuffle_down(s[2][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][3] += simd_shuffle_down(s[2][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][0] += simd_shuffle_down(s[3][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][1] += simd_shuffle_down(s[3][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][2] += simd_shuffle_down(s[3][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][3] += simd_shuffle_down(s[3][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][0] += simd_shuffle_down(s[4][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][1] += simd_shuffle_down(s[4][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][2] += simd_shuffle_down(s[4][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][3] += simd_shuffle_down(s[4][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][0] += simd_shuffle_down(s[5][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][1] += simd_shuffle_down(s[5][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][2] += simd_shuffle_down(s[5][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][3] += simd_shuffle_down(s[5][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][0] += simd_shuffle_down(s[6][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][1] += simd_shuffle_down(s[6][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][2] += simd_shuffle_down(s[6][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][3] += simd_shuffle_down(s[6][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][0] += simd_shuffle_down(s[7][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][1] += simd_shuffle_down(s[7][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][2] += simd_shuffle_down(s[7][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][3] += simd_shuffle_down(s[7][3], d);
        if (lane == 0) {
            { const uint j = sgid * 8u + 0u; if (j < 64u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 64u + j] = s[0][1]; scratch[0 + 128u + j] = s[0][2]; scratch[0 + 192u + j] = s[0][3]; } }
            { const uint j = sgid * 8u + 1u; if (j < 64u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 64u + j] = s[1][1]; scratch[0 + 128u + j] = s[1][2]; scratch[0 + 192u + j] = s[1][3]; } }
            { const uint j = sgid * 8u + 2u; if (j < 64u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 64u + j] = s[2][1]; scratch[0 + 128u + j] = s[2][2]; scratch[0 + 192u + j] = s[2][3]; } }
            { const uint j = sgid * 8u + 3u; if (j < 64u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 64u + j] = s[3][1]; scratch[0 + 128u + j] = s[3][2]; scratch[0 + 192u + j] = s[3][3]; } }
            { const uint j = sgid * 8u + 4u; if (j < 64u) { scratch[0 + 0u + j] = s[4][0]; scratch[0 + 64u + j] = s[4][1]; scratch[0 + 128u + j] = s[4][2]; scratch[0 + 192u + j] = s[4][3]; } }
            { const uint j = sgid * 8u + 5u; if (j < 64u) { scratch[0 + 0u + j] = s[5][0]; scratch[0 + 64u + j] = s[5][1]; scratch[0 + 128u + j] = s[5][2]; scratch[0 + 192u + j] = s[5][3]; } }
            { const uint j = sgid * 8u + 6u; if (j < 64u) { scratch[0 + 0u + j] = s[6][0]; scratch[0 + 64u + j] = s[6][1]; scratch[0 + 128u + j] = s[6][2]; scratch[0 + 192u + j] = s[6][3]; } }
            { const uint j = sgid * 8u + 7u; if (j < 64u) { scratch[0 + 0u + j] = s[7][0]; scratch[0 + 64u + j] = s[7][1]; scratch[0 + 128u + j] = s[7][2]; scratch[0 + 192u + j] = s[7][3]; } }
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            p4_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
