// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_fp4_64_4096
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 256 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void matvec_fp4_64_4096(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[64];
    __syncthreads();
    {
        const uint o = tid / 4u, lane = tid % 4u;
        float s = 0.0f;
        if (o < 64u) {
            const uint i = o / 64u, j = o % 64u;
            const float rs = float(float(p3_wg[(uint)(0) * 1u + ((j))]));
            for (uint p0 = lane * 16u; p0 < 4096u; p0 += 64u) {
                const uint grp = j * 256u + p0 / 16u;
                const float sg = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 256u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * rs;
                const uint2 wq = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 2048u + (uint)(0) * 1u + ((j * 2048u + p0 / 2u))]);
                const float4 x0 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p0 + 0u))]);
                const float4 x1 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p0 + 4u))]);
                const float4 x2 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p0 + 8u))]);
                const float4 x3 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p0 + 12u))]);
                float run = 0.0f;
                { const float2 w = fp4_pair((wq.x >> 0u) & 0xFFu); run += x0.x * w.x + x0.y * w.y; }
                { const float2 w = fp4_pair((wq.x >> 8u) & 0xFFu); run += x0.z * w.x + x0.w * w.y; }
                { const float2 w = fp4_pair((wq.x >> 16u) & 0xFFu); run += x1.x * w.x + x1.y * w.y; }
                { const float2 w = fp4_pair((wq.x >> 24u) & 0xFFu); run += x1.z * w.x + x1.w * w.y; }
                { const float2 w = fp4_pair((wq.y >> 0u) & 0xFFu); run += x2.x * w.x + x2.y * w.y; }
                { const float2 w = fp4_pair((wq.y >> 8u) & 0xFFu); run += x2.z * w.x + x2.w * w.y; }
                { const float2 w = fp4_pair((wq.y >> 16u) & 0xFFu); run += x3.x * w.x + x3.y * w.y; }
                { const float2 w = fp4_pair((wq.y >> 24u) & 0xFFu); run += x3.z * w.x + x3.w * w.y; }
                s += run * (sg * 16384.0f);
            }
        }
        for (uint d = 2u; d > 0; d /= 2) s += __shfl_down_sync(0xffffffffu, s, d);
        if (o < 64u && lane == 0) scratch[0 + o] = s;
    }
    __syncthreads();
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 64u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 64u) {
            p4_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
