// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_fp4_64_4096
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 256 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

constant float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
inline float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    return float2(as_type<half2>(((w & 0x00070007u) << 9u)
                               | ((w & 0x00080008u) << 12u)));
}
inline float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const uint bits = select(((e + 120u) << 23u) | (m << 20u),
                             as_type<uint>(float(m) * 0.001953125f), e == 0u);
    return as_type<float>(bits | ((b & 0x80u) << 24u));
}

kernel void matvec_fp4_64_4096(
    device const float* p0_x [[buffer(0)]],
    device const char* p1_wq [[buffer(1)]],
    device const char* p2_ws [[buffer(2)]],
    device const float* p3_wg [[buffer(3)]],
    device float* p4_y [[buffer(4)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[64];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 4u, lane = tid % 4u;
        float s = 0.0f;
        if (o < 64u) {
            const uint i = o / 64u, j = o % 64u;
            const float rs = float(float(p3_wg[(uint)(0) * 1u + ((j))]));
            for (uint p0 = lane * 16u; p0 < 4096u; p0 += 64u) {
                const uint grp = j * 256u + p0 / 16u;
                const float sg = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 256u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * rs;
                float run = 0.0f;
                for (uint u = 0; u < 16u; u += 2u) { const uint p = p0 + u; const uint bq = (uint)(uchar)(char(p1_wq[(uint)(0) * 2048u + (uint)(0) * 1u + ((j * 2048u + p0 / 2u + u / 2u))])); const float2 w = fp4_pair(bq); run += float(float(p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p))])) * w.x + float(float(p0_x[(uint)(0) * 4096u + (uint)(0) * 1u + ((i * 4096u + p + 1u))])) * w.y; }
                s += run * (sg * 16384.0f);
            }
        }
        for (uint d = 2u; d > 0; d /= 2) s += simd_shuffle_down(s, d);
        if (o < 64u && lane == 0) scratch[0 + o] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 64u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 64u) {
            p4_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
