// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_2_200_256
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 1600 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void batch_fp4_2_200_256(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[400];
    __syncthreads();
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[25][2];
        s[0][0] = 0.0f; s[0][1] = 0.0f;
        s[1][0] = 0.0f; s[1][1] = 0.0f;
        s[2][0] = 0.0f; s[2][1] = 0.0f;
        s[3][0] = 0.0f; s[3][1] = 0.0f;
        s[4][0] = 0.0f; s[4][1] = 0.0f;
        s[5][0] = 0.0f; s[5][1] = 0.0f;
        s[6][0] = 0.0f; s[6][1] = 0.0f;
        s[7][0] = 0.0f; s[7][1] = 0.0f;
        s[8][0] = 0.0f; s[8][1] = 0.0f;
        s[9][0] = 0.0f; s[9][1] = 0.0f;
        s[10][0] = 0.0f; s[10][1] = 0.0f;
        s[11][0] = 0.0f; s[11][1] = 0.0f;
        s[12][0] = 0.0f; s[12][1] = 0.0f;
        s[13][0] = 0.0f; s[13][1] = 0.0f;
        s[14][0] = 0.0f; s[14][1] = 0.0f;
        s[15][0] = 0.0f; s[15][1] = 0.0f;
        s[16][0] = 0.0f; s[16][1] = 0.0f;
        s[17][0] = 0.0f; s[17][1] = 0.0f;
        s[18][0] = 0.0f; s[18][1] = 0.0f;
        s[19][0] = 0.0f; s[19][1] = 0.0f;
        s[20][0] = 0.0f; s[20][1] = 0.0f;
        s[21][0] = 0.0f; s[21][1] = 0.0f;
        s[22][0] = 0.0f; s[22][1] = 0.0f;
        s[23][0] = 0.0f; s[23][1] = 0.0f;
        s[24][0] = 0.0f; s[24][1] = 0.0f;
        for (uint p0 = lane * 8u; p0 < 256u; p0 += 256u) {
            float sgr[25], mgr[25];
            { const uint j = min(sgid * 25u + 0u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[0] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[0] = 0.0f; }
            { const uint j = min(sgid * 25u + 1u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[1] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[1] = 0.0f; }
            { const uint j = min(sgid * 25u + 2u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[2] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[2] = 0.0f; }
            { const uint j = min(sgid * 25u + 3u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[3] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[3] = 0.0f; }
            { const uint j = min(sgid * 25u + 4u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[4] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[4] = 0.0f; }
            { const uint j = min(sgid * 25u + 5u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[5] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[5] = 0.0f; }
            { const uint j = min(sgid * 25u + 6u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[6] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[6] = 0.0f; }
            { const uint j = min(sgid * 25u + 7u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[7] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[7] = 0.0f; }
            { const uint j = min(sgid * 25u + 8u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[8] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[8] = 0.0f; }
            { const uint j = min(sgid * 25u + 9u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[9] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[9] = 0.0f; }
            { const uint j = min(sgid * 25u + 10u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[10] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[10] = 0.0f; }
            { const uint j = min(sgid * 25u + 11u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[11] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[11] = 0.0f; }
            { const uint j = min(sgid * 25u + 12u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[12] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[12] = 0.0f; }
            { const uint j = min(sgid * 25u + 13u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[13] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[13] = 0.0f; }
            { const uint j = min(sgid * 25u + 14u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[14] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[14] = 0.0f; }
            { const uint j = min(sgid * 25u + 15u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[15] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[15] = 0.0f; }
            { const uint j = min(sgid * 25u + 16u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[16] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[16] = 0.0f; }
            { const uint j = min(sgid * 25u + 17u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[17] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[17] = 0.0f; }
            { const uint j = min(sgid * 25u + 18u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[18] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[18] = 0.0f; }
            { const uint j = min(sgid * 25u + 19u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[19] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[19] = 0.0f; }
            { const uint j = min(sgid * 25u + 20u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[20] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[20] = 0.0f; }
            { const uint j = min(sgid * 25u + 21u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[21] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[21] = 0.0f; }
            { const uint j = min(sgid * 25u + 22u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[22] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[22] = 0.0f; }
            { const uint j = min(sgid * 25u + 23u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[23] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[23] = 0.0f; }
            { const uint j = min(sgid * 25u + 24u, 199u); const uint grp = j * 16u + p0 / 16u; sgr[24] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 16u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[24] = 0.0f; }
            for (uint u = 0; u < 8u; u += 2u) {
                const uint p = p0 + u;
                float xa[2][2];
                xa[0][0] = float(float(p0_x[(uint)(0) * 256u + (uint)(0) * 1u + ((p + 0u))]));
                xa[1][0] = float(float(p0_x[(uint)(0) * 256u + (uint)(0) * 1u + ((p + 256u))]));
                xa[0][1] = float(float(p0_x[(uint)(0) * 256u + (uint)(0) * 1u + ((p + 1u))]));
                xa[1][1] = float(float(p0_x[(uint)(0) * 256u + (uint)(0) * 1u + ((p + 257u))]));
                {
                    const uint j = min(sgid * 25u + 0u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[0]); const float w1 = (bq.y * sgr[0]);
                    s[0][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[0][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 1u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[1]); const float w1 = (bq.y * sgr[1]);
                    s[1][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[1][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 2u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[2]); const float w1 = (bq.y * sgr[2]);
                    s[2][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[2][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 3u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[3]); const float w1 = (bq.y * sgr[3]);
                    s[3][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[3][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 4u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[4]); const float w1 = (bq.y * sgr[4]);
                    s[4][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[4][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 5u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[5]); const float w1 = (bq.y * sgr[5]);
                    s[5][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[5][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 6u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[6]); const float w1 = (bq.y * sgr[6]);
                    s[6][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[6][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 7u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[7]); const float w1 = (bq.y * sgr[7]);
                    s[7][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[7][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 8u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[8]); const float w1 = (bq.y * sgr[8]);
                    s[8][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[8][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 9u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[9]); const float w1 = (bq.y * sgr[9]);
                    s[9][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[9][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 10u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[10]); const float w1 = (bq.y * sgr[10]);
                    s[10][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[10][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 11u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[11]); const float w1 = (bq.y * sgr[11]);
                    s[11][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[11][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 12u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[12]); const float w1 = (bq.y * sgr[12]);
                    s[12][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[12][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 13u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[13]); const float w1 = (bq.y * sgr[13]);
                    s[13][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[13][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 14u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[14]); const float w1 = (bq.y * sgr[14]);
                    s[14][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[14][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 15u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[15]); const float w1 = (bq.y * sgr[15]);
                    s[15][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[15][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 16u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[16]); const float w1 = (bq.y * sgr[16]);
                    s[16][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[16][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 17u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[17]); const float w1 = (bq.y * sgr[17]);
                    s[17][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[17][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 18u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[18]); const float w1 = (bq.y * sgr[18]);
                    s[18][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[18][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 19u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[19]); const float w1 = (bq.y * sgr[19]);
                    s[19][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[19][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 20u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[20]); const float w1 = (bq.y * sgr[20]);
                    s[20][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[20][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 21u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[21]); const float w1 = (bq.y * sgr[21]);
                    s[21][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[21][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 22u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[22]); const float w1 = (bq.y * sgr[22]);
                    s[22][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[22][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 23u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[23]); const float w1 = (bq.y * sgr[23]);
                    s[23][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[23][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
                {
                    const uint j = min(sgid * 25u + 24u, 199u);
                    const float2 bq = fp4_pair((uint)(uchar)(char(p1_wq[(uint)(0) * 128u + (uint)(0) * 1u + ((j * 128u + p0 / 2u + u / 2u))]))); const float w0 = (bq.x * sgr[24]); const float w1 = (bq.y * sgr[24]);
                    s[24][0] += xa[0][0] * w0 + xa[0][1] * w1;
                    s[24][1] += xa[1][0] * w0 + xa[1][1] * w1;
                }
            }
        }
        for (uint d = 16u; d > 0; d /= 2) s[0][0] += __shfl_down_sync(0xffffffffu, s[0][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][1] += __shfl_down_sync(0xffffffffu, s[0][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][0] += __shfl_down_sync(0xffffffffu, s[1][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][1] += __shfl_down_sync(0xffffffffu, s[1][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][0] += __shfl_down_sync(0xffffffffu, s[2][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][1] += __shfl_down_sync(0xffffffffu, s[2][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][0] += __shfl_down_sync(0xffffffffu, s[3][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][1] += __shfl_down_sync(0xffffffffu, s[3][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][0] += __shfl_down_sync(0xffffffffu, s[4][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][1] += __shfl_down_sync(0xffffffffu, s[4][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][0] += __shfl_down_sync(0xffffffffu, s[5][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][1] += __shfl_down_sync(0xffffffffu, s[5][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][0] += __shfl_down_sync(0xffffffffu, s[6][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][1] += __shfl_down_sync(0xffffffffu, s[6][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][0] += __shfl_down_sync(0xffffffffu, s[7][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][1] += __shfl_down_sync(0xffffffffu, s[7][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[8][0] += __shfl_down_sync(0xffffffffu, s[8][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[8][1] += __shfl_down_sync(0xffffffffu, s[8][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[9][0] += __shfl_down_sync(0xffffffffu, s[9][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[9][1] += __shfl_down_sync(0xffffffffu, s[9][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[10][0] += __shfl_down_sync(0xffffffffu, s[10][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[10][1] += __shfl_down_sync(0xffffffffu, s[10][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[11][0] += __shfl_down_sync(0xffffffffu, s[11][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[11][1] += __shfl_down_sync(0xffffffffu, s[11][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[12][0] += __shfl_down_sync(0xffffffffu, s[12][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[12][1] += __shfl_down_sync(0xffffffffu, s[12][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[13][0] += __shfl_down_sync(0xffffffffu, s[13][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[13][1] += __shfl_down_sync(0xffffffffu, s[13][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[14][0] += __shfl_down_sync(0xffffffffu, s[14][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[14][1] += __shfl_down_sync(0xffffffffu, s[14][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[15][0] += __shfl_down_sync(0xffffffffu, s[15][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[15][1] += __shfl_down_sync(0xffffffffu, s[15][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[16][0] += __shfl_down_sync(0xffffffffu, s[16][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[16][1] += __shfl_down_sync(0xffffffffu, s[16][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[17][0] += __shfl_down_sync(0xffffffffu, s[17][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[17][1] += __shfl_down_sync(0xffffffffu, s[17][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[18][0] += __shfl_down_sync(0xffffffffu, s[18][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[18][1] += __shfl_down_sync(0xffffffffu, s[18][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[19][0] += __shfl_down_sync(0xffffffffu, s[19][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[19][1] += __shfl_down_sync(0xffffffffu, s[19][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[20][0] += __shfl_down_sync(0xffffffffu, s[20][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[20][1] += __shfl_down_sync(0xffffffffu, s[20][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[21][0] += __shfl_down_sync(0xffffffffu, s[21][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[21][1] += __shfl_down_sync(0xffffffffu, s[21][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[22][0] += __shfl_down_sync(0xffffffffu, s[22][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[22][1] += __shfl_down_sync(0xffffffffu, s[22][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[23][0] += __shfl_down_sync(0xffffffffu, s[23][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[23][1] += __shfl_down_sync(0xffffffffu, s[23][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[24][0] += __shfl_down_sync(0xffffffffu, s[24][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[24][1] += __shfl_down_sync(0xffffffffu, s[24][1], d);
        if (lane == 0) {
            { const uint j = sgid * 25u + 0u; if (j < 200u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 200u + j] = s[0][1]; } }
            { const uint j = sgid * 25u + 1u; if (j < 200u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 200u + j] = s[1][1]; } }
            { const uint j = sgid * 25u + 2u; if (j < 200u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 200u + j] = s[2][1]; } }
            { const uint j = sgid * 25u + 3u; if (j < 200u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 200u + j] = s[3][1]; } }
            { const uint j = sgid * 25u + 4u; if (j < 200u) { scratch[0 + 0u + j] = s[4][0]; scratch[0 + 200u + j] = s[4][1]; } }
            { const uint j = sgid * 25u + 5u; if (j < 200u) { scratch[0 + 0u + j] = s[5][0]; scratch[0 + 200u + j] = s[5][1]; } }
            { const uint j = sgid * 25u + 6u; if (j < 200u) { scratch[0 + 0u + j] = s[6][0]; scratch[0 + 200u + j] = s[6][1]; } }
            { const uint j = sgid * 25u + 7u; if (j < 200u) { scratch[0 + 0u + j] = s[7][0]; scratch[0 + 200u + j] = s[7][1]; } }
            { const uint j = sgid * 25u + 8u; if (j < 200u) { scratch[0 + 0u + j] = s[8][0]; scratch[0 + 200u + j] = s[8][1]; } }
            { const uint j = sgid * 25u + 9u; if (j < 200u) { scratch[0 + 0u + j] = s[9][0]; scratch[0 + 200u + j] = s[9][1]; } }
            { const uint j = sgid * 25u + 10u; if (j < 200u) { scratch[0 + 0u + j] = s[10][0]; scratch[0 + 200u + j] = s[10][1]; } }
            { const uint j = sgid * 25u + 11u; if (j < 200u) { scratch[0 + 0u + j] = s[11][0]; scratch[0 + 200u + j] = s[11][1]; } }
            { const uint j = sgid * 25u + 12u; if (j < 200u) { scratch[0 + 0u + j] = s[12][0]; scratch[0 + 200u + j] = s[12][1]; } }
            { const uint j = sgid * 25u + 13u; if (j < 200u) { scratch[0 + 0u + j] = s[13][0]; scratch[0 + 200u + j] = s[13][1]; } }
            { const uint j = sgid * 25u + 14u; if (j < 200u) { scratch[0 + 0u + j] = s[14][0]; scratch[0 + 200u + j] = s[14][1]; } }
            { const uint j = sgid * 25u + 15u; if (j < 200u) { scratch[0 + 0u + j] = s[15][0]; scratch[0 + 200u + j] = s[15][1]; } }
            { const uint j = sgid * 25u + 16u; if (j < 200u) { scratch[0 + 0u + j] = s[16][0]; scratch[0 + 200u + j] = s[16][1]; } }
            { const uint j = sgid * 25u + 17u; if (j < 200u) { scratch[0 + 0u + j] = s[17][0]; scratch[0 + 200u + j] = s[17][1]; } }
            { const uint j = sgid * 25u + 18u; if (j < 200u) { scratch[0 + 0u + j] = s[18][0]; scratch[0 + 200u + j] = s[18][1]; } }
            { const uint j = sgid * 25u + 19u; if (j < 200u) { scratch[0 + 0u + j] = s[19][0]; scratch[0 + 200u + j] = s[19][1]; } }
            { const uint j = sgid * 25u + 20u; if (j < 200u) { scratch[0 + 0u + j] = s[20][0]; scratch[0 + 200u + j] = s[20][1]; } }
            { const uint j = sgid * 25u + 21u; if (j < 200u) { scratch[0 + 0u + j] = s[21][0]; scratch[0 + 200u + j] = s[21][1]; } }
            { const uint j = sgid * 25u + 22u; if (j < 200u) { scratch[0 + 0u + j] = s[22][0]; scratch[0 + 200u + j] = s[22][1]; } }
            { const uint j = sgid * 25u + 23u; if (j < 200u) { scratch[0 + 0u + j] = s[23][0]; scratch[0 + 200u + j] = s[23][1]; } }
            { const uint j = sgid * 25u + 24u; if (j < 200u) { scratch[0 + 0u + j] = s[24][0]; scratch[0 + 200u + j] = s[24][1]; } }
        }
    }
    __syncthreads();
    float v5[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 400u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 400u) {
            p4_y[(uint)(0) * 200u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
