// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : batch_fp4_4_64_512
// target : nvidia-ada
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 1024 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void batch_fp4_4_64_512(
    const float* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    __shared__ float scratch[256];
    __syncthreads();
    {
        const uint sgid = tid / 32u, lane = tid % 32u;
        float s[8][4];
        s[0][0] = 0.0f; s[0][1] = 0.0f; s[0][2] = 0.0f; s[0][3] = 0.0f;
        s[1][0] = 0.0f; s[1][1] = 0.0f; s[1][2] = 0.0f; s[1][3] = 0.0f;
        s[2][0] = 0.0f; s[2][1] = 0.0f; s[2][2] = 0.0f; s[2][3] = 0.0f;
        s[3][0] = 0.0f; s[3][1] = 0.0f; s[3][2] = 0.0f; s[3][3] = 0.0f;
        s[4][0] = 0.0f; s[4][1] = 0.0f; s[4][2] = 0.0f; s[4][3] = 0.0f;
        s[5][0] = 0.0f; s[5][1] = 0.0f; s[5][2] = 0.0f; s[5][3] = 0.0f;
        s[6][0] = 0.0f; s[6][1] = 0.0f; s[6][2] = 0.0f; s[6][3] = 0.0f;
        s[7][0] = 0.0f; s[7][1] = 0.0f; s[7][2] = 0.0f; s[7][3] = 0.0f;
        for (uint p0 = lane * 16u; p0 < 512u; p0 += 512u) {
            float sgr[8], mgr[8];
            { const uint j = min(sgid * 8u + 0u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[0] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[0] = 0.0f; }
            { const uint j = min(sgid * 8u + 1u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[1] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[1] = 0.0f; }
            { const uint j = min(sgid * 8u + 2u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[2] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[2] = 0.0f; }
            { const uint j = min(sgid * 8u + 3u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[3] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[3] = 0.0f; }
            { const uint j = min(sgid * 8u + 4u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[4] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[4] = 0.0f; }
            { const uint j = min(sgid * 8u + 5u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[5] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[5] = 0.0f; }
            { const uint j = min(sgid * 8u + 6u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[6] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[6] = 0.0f; }
            { const uint j = min(sgid * 8u + 7u, 63u); const uint grp = j * 32u + p0 / 16u; sgr[7] = fp8_e4m3((uint)(uchar)(char(p2_ws[(uint)(0) * 32u + (uint)(0) * 1u + ((grp))])) & 0xFFu) * float(float(p3_wg[(uint)(0) * 1u + ((j))])) * 16384.0f; mgr[7] = 0.0f; }
            uint2 wq[8];
            { const uint j = min(sgid * 8u + 0u, 63u); wq[0] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 1u, 63u); wq[1] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 2u, 63u); wq[2] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 3u, 63u); wq[3] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 4u, 63u); wq[4] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 5u, 63u); wq[5] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 6u, 63u); wq[6] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            { const uint j = min(sgid * 8u + 7u, 63u); wq[7] = *reinterpret_cast<const uint2*>(&p1_wq[(uint)(0) * 256u + (uint)(0) * 1u + ((j * 256u + p0 / 2u))]); }
            {
                const float4 x0 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((0u + p0 + 0u))]);
                const float4 x1 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((512u + p0 + 0u))]);
                const float4 x2 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1024u + p0 + 0u))]);
                const float4 x3 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1536u + p0 + 0u))]);
                { const float2 w = fp4_pair((wq[0].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.x * w0 + x0.y * w1; s[0][1] += x1.x * w0 + x1.y * w1; s[0][2] += x2.x * w0 + x2.y * w1; s[0][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[0].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.z * w0 + x0.w * w1; s[0][1] += x1.z * w0 + x1.w * w1; s[0][2] += x2.z * w0 + x2.w * w1; s[0][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[1].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.x * w0 + x0.y * w1; s[1][1] += x1.x * w0 + x1.y * w1; s[1][2] += x2.x * w0 + x2.y * w1; s[1][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[1].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.z * w0 + x0.w * w1; s[1][1] += x1.z * w0 + x1.w * w1; s[1][2] += x2.z * w0 + x2.w * w1; s[1][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[2].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.x * w0 + x0.y * w1; s[2][1] += x1.x * w0 + x1.y * w1; s[2][2] += x2.x * w0 + x2.y * w1; s[2][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[2].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.z * w0 + x0.w * w1; s[2][1] += x1.z * w0 + x1.w * w1; s[2][2] += x2.z * w0 + x2.w * w1; s[2][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[3].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.x * w0 + x0.y * w1; s[3][1] += x1.x * w0 + x1.y * w1; s[3][2] += x2.x * w0 + x2.y * w1; s[3][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[3].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.z * w0 + x0.w * w1; s[3][1] += x1.z * w0 + x1.w * w1; s[3][2] += x2.z * w0 + x2.w * w1; s[3][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[4].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.x * w0 + x0.y * w1; s[4][1] += x1.x * w0 + x1.y * w1; s[4][2] += x2.x * w0 + x2.y * w1; s[4][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[4].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.z * w0 + x0.w * w1; s[4][1] += x1.z * w0 + x1.w * w1; s[4][2] += x2.z * w0 + x2.w * w1; s[4][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[5].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.x * w0 + x0.y * w1; s[5][1] += x1.x * w0 + x1.y * w1; s[5][2] += x2.x * w0 + x2.y * w1; s[5][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[5].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.z * w0 + x0.w * w1; s[5][1] += x1.z * w0 + x1.w * w1; s[5][2] += x2.z * w0 + x2.w * w1; s[5][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[6].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.x * w0 + x0.y * w1; s[6][1] += x1.x * w0 + x1.y * w1; s[6][2] += x2.x * w0 + x2.y * w1; s[6][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[6].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.z * w0 + x0.w * w1; s[6][1] += x1.z * w0 + x1.w * w1; s[6][2] += x2.z * w0 + x2.w * w1; s[6][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[7].x >> 0u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.x * w0 + x0.y * w1; s[7][1] += x1.x * w0 + x1.y * w1; s[7][2] += x2.x * w0 + x2.y * w1; s[7][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[7].x >> 8u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.z * w0 + x0.w * w1; s[7][1] += x1.z * w0 + x1.w * w1; s[7][2] += x2.z * w0 + x2.w * w1; s[7][3] += x3.z * w0 + x3.w * w1; }
            }
            {
                const float4 x0 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((0u + p0 + 4u))]);
                const float4 x1 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((512u + p0 + 4u))]);
                const float4 x2 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1024u + p0 + 4u))]);
                const float4 x3 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1536u + p0 + 4u))]);
                { const float2 w = fp4_pair((wq[0].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.x * w0 + x0.y * w1; s[0][1] += x1.x * w0 + x1.y * w1; s[0][2] += x2.x * w0 + x2.y * w1; s[0][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[0].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.z * w0 + x0.w * w1; s[0][1] += x1.z * w0 + x1.w * w1; s[0][2] += x2.z * w0 + x2.w * w1; s[0][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[1].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.x * w0 + x0.y * w1; s[1][1] += x1.x * w0 + x1.y * w1; s[1][2] += x2.x * w0 + x2.y * w1; s[1][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[1].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.z * w0 + x0.w * w1; s[1][1] += x1.z * w0 + x1.w * w1; s[1][2] += x2.z * w0 + x2.w * w1; s[1][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[2].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.x * w0 + x0.y * w1; s[2][1] += x1.x * w0 + x1.y * w1; s[2][2] += x2.x * w0 + x2.y * w1; s[2][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[2].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.z * w0 + x0.w * w1; s[2][1] += x1.z * w0 + x1.w * w1; s[2][2] += x2.z * w0 + x2.w * w1; s[2][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[3].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.x * w0 + x0.y * w1; s[3][1] += x1.x * w0 + x1.y * w1; s[3][2] += x2.x * w0 + x2.y * w1; s[3][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[3].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.z * w0 + x0.w * w1; s[3][1] += x1.z * w0 + x1.w * w1; s[3][2] += x2.z * w0 + x2.w * w1; s[3][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[4].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.x * w0 + x0.y * w1; s[4][1] += x1.x * w0 + x1.y * w1; s[4][2] += x2.x * w0 + x2.y * w1; s[4][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[4].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.z * w0 + x0.w * w1; s[4][1] += x1.z * w0 + x1.w * w1; s[4][2] += x2.z * w0 + x2.w * w1; s[4][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[5].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.x * w0 + x0.y * w1; s[5][1] += x1.x * w0 + x1.y * w1; s[5][2] += x2.x * w0 + x2.y * w1; s[5][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[5].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.z * w0 + x0.w * w1; s[5][1] += x1.z * w0 + x1.w * w1; s[5][2] += x2.z * w0 + x2.w * w1; s[5][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[6].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.x * w0 + x0.y * w1; s[6][1] += x1.x * w0 + x1.y * w1; s[6][2] += x2.x * w0 + x2.y * w1; s[6][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[6].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.z * w0 + x0.w * w1; s[6][1] += x1.z * w0 + x1.w * w1; s[6][2] += x2.z * w0 + x2.w * w1; s[6][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[7].x >> 16u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.x * w0 + x0.y * w1; s[7][1] += x1.x * w0 + x1.y * w1; s[7][2] += x2.x * w0 + x2.y * w1; s[7][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[7].x >> 24u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.z * w0 + x0.w * w1; s[7][1] += x1.z * w0 + x1.w * w1; s[7][2] += x2.z * w0 + x2.w * w1; s[7][3] += x3.z * w0 + x3.w * w1; }
            }
            {
                const float4 x0 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((0u + p0 + 8u))]);
                const float4 x1 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((512u + p0 + 8u))]);
                const float4 x2 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1024u + p0 + 8u))]);
                const float4 x3 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1536u + p0 + 8u))]);
                { const float2 w = fp4_pair((wq[0].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.x * w0 + x0.y * w1; s[0][1] += x1.x * w0 + x1.y * w1; s[0][2] += x2.x * w0 + x2.y * w1; s[0][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[0].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.z * w0 + x0.w * w1; s[0][1] += x1.z * w0 + x1.w * w1; s[0][2] += x2.z * w0 + x2.w * w1; s[0][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[1].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.x * w0 + x0.y * w1; s[1][1] += x1.x * w0 + x1.y * w1; s[1][2] += x2.x * w0 + x2.y * w1; s[1][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[1].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.z * w0 + x0.w * w1; s[1][1] += x1.z * w0 + x1.w * w1; s[1][2] += x2.z * w0 + x2.w * w1; s[1][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[2].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.x * w0 + x0.y * w1; s[2][1] += x1.x * w0 + x1.y * w1; s[2][2] += x2.x * w0 + x2.y * w1; s[2][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[2].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.z * w0 + x0.w * w1; s[2][1] += x1.z * w0 + x1.w * w1; s[2][2] += x2.z * w0 + x2.w * w1; s[2][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[3].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.x * w0 + x0.y * w1; s[3][1] += x1.x * w0 + x1.y * w1; s[3][2] += x2.x * w0 + x2.y * w1; s[3][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[3].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.z * w0 + x0.w * w1; s[3][1] += x1.z * w0 + x1.w * w1; s[3][2] += x2.z * w0 + x2.w * w1; s[3][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[4].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.x * w0 + x0.y * w1; s[4][1] += x1.x * w0 + x1.y * w1; s[4][2] += x2.x * w0 + x2.y * w1; s[4][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[4].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.z * w0 + x0.w * w1; s[4][1] += x1.z * w0 + x1.w * w1; s[4][2] += x2.z * w0 + x2.w * w1; s[4][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[5].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.x * w0 + x0.y * w1; s[5][1] += x1.x * w0 + x1.y * w1; s[5][2] += x2.x * w0 + x2.y * w1; s[5][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[5].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.z * w0 + x0.w * w1; s[5][1] += x1.z * w0 + x1.w * w1; s[5][2] += x2.z * w0 + x2.w * w1; s[5][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[6].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.x * w0 + x0.y * w1; s[6][1] += x1.x * w0 + x1.y * w1; s[6][2] += x2.x * w0 + x2.y * w1; s[6][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[6].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.z * w0 + x0.w * w1; s[6][1] += x1.z * w0 + x1.w * w1; s[6][2] += x2.z * w0 + x2.w * w1; s[6][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[7].y >> 0u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.x * w0 + x0.y * w1; s[7][1] += x1.x * w0 + x1.y * w1; s[7][2] += x2.x * w0 + x2.y * w1; s[7][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[7].y >> 8u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.z * w0 + x0.w * w1; s[7][1] += x1.z * w0 + x1.w * w1; s[7][2] += x2.z * w0 + x2.w * w1; s[7][3] += x3.z * w0 + x3.w * w1; }
            }
            {
                const float4 x0 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((0u + p0 + 12u))]);
                const float4 x1 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((512u + p0 + 12u))]);
                const float4 x2 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1024u + p0 + 12u))]);
                const float4 x3 = *reinterpret_cast<const float4*>(&p0_x[(uint)(0) * 512u + (uint)(0) * 1u + ((1536u + p0 + 12u))]);
                { const float2 w = fp4_pair((wq[0].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.x * w0 + x0.y * w1; s[0][1] += x1.x * w0 + x1.y * w1; s[0][2] += x2.x * w0 + x2.y * w1; s[0][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[0].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[0], w1 = w.y * sgr[0]; s[0][0] += x0.z * w0 + x0.w * w1; s[0][1] += x1.z * w0 + x1.w * w1; s[0][2] += x2.z * w0 + x2.w * w1; s[0][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[1].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.x * w0 + x0.y * w1; s[1][1] += x1.x * w0 + x1.y * w1; s[1][2] += x2.x * w0 + x2.y * w1; s[1][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[1].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[1], w1 = w.y * sgr[1]; s[1][0] += x0.z * w0 + x0.w * w1; s[1][1] += x1.z * w0 + x1.w * w1; s[1][2] += x2.z * w0 + x2.w * w1; s[1][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[2].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.x * w0 + x0.y * w1; s[2][1] += x1.x * w0 + x1.y * w1; s[2][2] += x2.x * w0 + x2.y * w1; s[2][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[2].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[2], w1 = w.y * sgr[2]; s[2][0] += x0.z * w0 + x0.w * w1; s[2][1] += x1.z * w0 + x1.w * w1; s[2][2] += x2.z * w0 + x2.w * w1; s[2][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[3].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.x * w0 + x0.y * w1; s[3][1] += x1.x * w0 + x1.y * w1; s[3][2] += x2.x * w0 + x2.y * w1; s[3][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[3].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[3], w1 = w.y * sgr[3]; s[3][0] += x0.z * w0 + x0.w * w1; s[3][1] += x1.z * w0 + x1.w * w1; s[3][2] += x2.z * w0 + x2.w * w1; s[3][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[4].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.x * w0 + x0.y * w1; s[4][1] += x1.x * w0 + x1.y * w1; s[4][2] += x2.x * w0 + x2.y * w1; s[4][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[4].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[4], w1 = w.y * sgr[4]; s[4][0] += x0.z * w0 + x0.w * w1; s[4][1] += x1.z * w0 + x1.w * w1; s[4][2] += x2.z * w0 + x2.w * w1; s[4][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[5].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.x * w0 + x0.y * w1; s[5][1] += x1.x * w0 + x1.y * w1; s[5][2] += x2.x * w0 + x2.y * w1; s[5][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[5].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[5], w1 = w.y * sgr[5]; s[5][0] += x0.z * w0 + x0.w * w1; s[5][1] += x1.z * w0 + x1.w * w1; s[5][2] += x2.z * w0 + x2.w * w1; s[5][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[6].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.x * w0 + x0.y * w1; s[6][1] += x1.x * w0 + x1.y * w1; s[6][2] += x2.x * w0 + x2.y * w1; s[6][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[6].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[6], w1 = w.y * sgr[6]; s[6][0] += x0.z * w0 + x0.w * w1; s[6][1] += x1.z * w0 + x1.w * w1; s[6][2] += x2.z * w0 + x2.w * w1; s[6][3] += x3.z * w0 + x3.w * w1; }
                { const float2 w = fp4_pair((wq[7].y >> 16u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.x * w0 + x0.y * w1; s[7][1] += x1.x * w0 + x1.y * w1; s[7][2] += x2.x * w0 + x2.y * w1; s[7][3] += x3.x * w0 + x3.y * w1; }
                { const float2 w = fp4_pair((wq[7].y >> 24u) & 0xFFu); const float w0 = w.x * sgr[7], w1 = w.y * sgr[7]; s[7][0] += x0.z * w0 + x0.w * w1; s[7][1] += x1.z * w0 + x1.w * w1; s[7][2] += x2.z * w0 + x2.w * w1; s[7][3] += x3.z * w0 + x3.w * w1; }
            }
        }
        for (uint d = 16u; d > 0; d /= 2) s[0][0] += __shfl_down_sync(0xffffffffu, s[0][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][1] += __shfl_down_sync(0xffffffffu, s[0][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][2] += __shfl_down_sync(0xffffffffu, s[0][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[0][3] += __shfl_down_sync(0xffffffffu, s[0][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][0] += __shfl_down_sync(0xffffffffu, s[1][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][1] += __shfl_down_sync(0xffffffffu, s[1][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][2] += __shfl_down_sync(0xffffffffu, s[1][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[1][3] += __shfl_down_sync(0xffffffffu, s[1][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][0] += __shfl_down_sync(0xffffffffu, s[2][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][1] += __shfl_down_sync(0xffffffffu, s[2][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][2] += __shfl_down_sync(0xffffffffu, s[2][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[2][3] += __shfl_down_sync(0xffffffffu, s[2][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][0] += __shfl_down_sync(0xffffffffu, s[3][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][1] += __shfl_down_sync(0xffffffffu, s[3][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][2] += __shfl_down_sync(0xffffffffu, s[3][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[3][3] += __shfl_down_sync(0xffffffffu, s[3][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][0] += __shfl_down_sync(0xffffffffu, s[4][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][1] += __shfl_down_sync(0xffffffffu, s[4][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][2] += __shfl_down_sync(0xffffffffu, s[4][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[4][3] += __shfl_down_sync(0xffffffffu, s[4][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][0] += __shfl_down_sync(0xffffffffu, s[5][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][1] += __shfl_down_sync(0xffffffffu, s[5][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][2] += __shfl_down_sync(0xffffffffu, s[5][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[5][3] += __shfl_down_sync(0xffffffffu, s[5][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][0] += __shfl_down_sync(0xffffffffu, s[6][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][1] += __shfl_down_sync(0xffffffffu, s[6][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][2] += __shfl_down_sync(0xffffffffu, s[6][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[6][3] += __shfl_down_sync(0xffffffffu, s[6][3], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][0] += __shfl_down_sync(0xffffffffu, s[7][0], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][1] += __shfl_down_sync(0xffffffffu, s[7][1], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][2] += __shfl_down_sync(0xffffffffu, s[7][2], d);
        for (uint d = 16u; d > 0; d /= 2) s[7][3] += __shfl_down_sync(0xffffffffu, s[7][3], d);
        if (lane == 0) {
            { const uint j = sgid * 8u + 0u; if (j < 64u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 64u + j] = s[0][1]; scratch[0 + 128u + j] = s[0][2]; scratch[0 + 192u + j] = s[0][3]; } }
            { const uint j = sgid * 8u + 1u; if (j < 64u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 64u + j] = s[1][1]; scratch[0 + 128u + j] = s[1][2]; scratch[0 + 192u + j] = s[1][3]; } }
            { const uint j = sgid * 8u + 2u; if (j < 64u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 64u + j] = s[2][1]; scratch[0 + 128u + j] = s[2][2]; scratch[0 + 192u + j] = s[2][3]; } }
            { const uint j = sgid * 8u + 3u; if (j < 64u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 64u + j] = s[3][1]; scratch[0 + 128u + j] = s[3][2]; scratch[0 + 192u + j] = s[3][3]; } }
            { const uint j = sgid * 8u + 4u; if (j < 64u) { scratch[0 + 0u + j] = s[4][0]; scratch[0 + 64u + j] = s[4][1]; scratch[0 + 128u + j] = s[4][2]; scratch[0 + 192u + j] = s[4][3]; } }
            { const uint j = sgid * 8u + 5u; if (j < 64u) { scratch[0 + 0u + j] = s[5][0]; scratch[0 + 64u + j] = s[5][1]; scratch[0 + 128u + j] = s[5][2]; scratch[0 + 192u + j] = s[5][3]; } }
            { const uint j = sgid * 8u + 6u; if (j < 64u) { scratch[0 + 0u + j] = s[6][0]; scratch[0 + 64u + j] = s[6][1]; scratch[0 + 128u + j] = s[6][2]; scratch[0 + 192u + j] = s[6][3]; } }
            { const uint j = sgid * 8u + 7u; if (j < 64u) { scratch[0 + 0u + j] = s[7][0]; scratch[0 + 64u + j] = s[7][1]; scratch[0 + 128u + j] = s[7][2]; scratch[0 + 192u + j] = s[7][3]; } }
        }
    }
    __syncthreads();
    float v5[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            v5[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 256u) {
            p4_y[(uint)(0) * 64u + (uint)(0) * 1u + (e)] = float(float(v5[k]));
        }
    }
}
