// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_16_100
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 64 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void matvec_16_100(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    threadgroup float scratch[16];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    {
        const uint o = tid / 16u, lane = tid % 16u;
        float s = 0.0f;
        if (o < 16u) {
            const uint i = o / 16u, j = o % 16u;
            for (uint p = lane; p < 100u; p += 16u) s += float(float(p0_x[(uint)(0) * 100u + (uint)(0) * 1u + ((i * 100u + p))])) * float(float(p1_w[(uint)(0) * 100u + (uint)(0) * 1u + ((j * 100u + p))]));
        }
        for (uint d = 8u; d > 0; d /= 2) s += simd_shuffle_down(s, d);
        if (o < 16u && lane == 0) scratch[0 + o] = s;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float v2[1];
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 16u) {
            v2[k] = float(scratch[0 + e]);
        }
    }
    for (uint k = 0; k < 1u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 16u) {
            p2_y[(uint)(0) * 16u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
