// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : gemm_fp4_256_128_128_128_128_64
// target : nvidia-ada
// launch : 2 threadgroups x 256 threads
// tg mem : 36864 B tiles + 0 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

#include <mma.h>

__constant__ float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
__device__ __forceinline__ float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    const uint bits = ((w & 0x00070007u) << 9u)
                    | ((w & 0x00080008u) << 12u);
    __half2 h;
    memcpy(&h, &bits, sizeof(h));
    return __half22float2(h);
}
__device__ __forceinline__ float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const float sub = float(m) * 0.001953125f;
    uint subbits;
    memcpy(&subbits, &sub, sizeof(subbits));
    const uint bits = (e == 0u) ? subbits : (((e + 120u) << 23u) | (m << 20u));
    const uint out = bits | ((b & 0x80u) << 24u);
    float r;
    memcpy(&r, &out, sizeof(r));
    return r;
}

extern "C" __global__ void gemm_fp4_256_128_128_128_128_64(
    const __half* __restrict__ p0_x,
    const char* __restrict__ p1_wq,
    const char* __restrict__ p2_ws,
    const float* __restrict__ p3_wg,
    float* __restrict__ p4_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x, gid2 = blockIdx.y;
    __shared__ __align__(32) float4 arena4[2304];
    uchar* arena = (uchar*)arena4;
    nvcuda::wmma::fragment<nvcuda::wmma::accumulator, 16, 16, 16, float> v2[4][2];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) nvcuda::wmma::fill_fragment(v2[i][j], 0.0f);
    nvcuda::wmma::fragment<nvcuda::wmma::accumulator, 16, 16, 16, float> v4[4][2];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) v4[i][j] = v2[i][j];
    for (uint v3 = 0u; v3 < 2u; ++v3) {
        __half* v5 = (__half*)(arena + 0);
        __syncthreads();
        for (uint e = tid; e < 1024u; e += 256u) {
            const uint r = e / 8u, c = (e % 8u) * 8u;
            *reinterpret_cast<uint4*>(&v5[r * 72u + c]) = *reinterpret_cast<const uint4*>(&p0_x[((uint)(0 + 128 * gid) + (((r * 64u + c)) / 64u % 128u)) * 128u + ((uint)(0 + 64 * v3) + (((r * 64u + c)) / 1u % 64u)) * 1u]);
        }
        __syncthreads();
        __half* v10 = (__half*)(arena + 18432);
        __syncthreads();
        for (uint gi = tid; gi < 512u; gi += 256u) {
            const uint rr = gi / 4u, c0 = (gi % 4u) * 16u;
            const float sc = fp8_e4m3((uint)(uchar)(char(p2_ws[((uint)(0 + 128 * gid2) + (((gi)) / 4u % 128u)) * 8u + ((uint)(0 + 4 * v3) + (((gi)) / 1u % 4u)) * 1u])) & 0xFFu) * float(p3_wg[(uint)(0 + 128 * gid2) * 1u + ((rr))]) * 16384.0f;
            const uint2 w = *reinterpret_cast<const uint2*>(&p1_wq[((uint)(0 + 128 * gid2) + (((rr * 32u + c0 / 2u)) / 32u % 128u)) * 64u + ((uint)(0 + 32 * v3) + (((rr * 32u + c0 / 2u)) / 1u % 32u)) * 1u]);
            __half2 h[8];
            for (uint b = 0; b < 8u; ++b) {
                const float2 v = fp4_pair(((b < 4u ? w.x : w.y) >> (8u * (b & 3u))) & 0xFFu);
                h[b] = __floats2half2_rn(v.x * sc, v.y * sc);
            }
            *reinterpret_cast<uint4*>(&v10[rr * 72u + c0]) = *reinterpret_cast<uint4*>(&h[0]);
            *reinterpret_cast<uint4*>(&v10[rr * 72u + c0] + 8) = *reinterpret_cast<uint4*>(&h[4]);
        }
        __syncthreads();
        {
            nvcuda::wmma::fragment<nvcuda::wmma::matrix_a, 16, 16, 16, __half, nvcuda::wmma::row_major> fa[4];
            nvcuda::wmma::fragment<nvcuda::wmma::matrix_b, 16, 16, 16, __half, nvcuda::wmma::col_major> fb[2];
            for (uint kk = 0; kk < 64u; kk += 16u) {
                for (uint i = 0; i < 4u; ++i) nvcuda::wmma::load_matrix_sync(fa[i], v5 + ((tid / 128u) * 64u + i * 16u) * 72u + kk, 72u);
                for (uint j = 0; j < 2u; ++j) nvcuda::wmma::load_matrix_sync(fb[j], v10 + ((tid / 32u % 4u) * 32u + j * 16u) * 72u + kk, 72u);
                for (uint i = 0; i < 4u; ++i)
                    for (uint j = 0; j < 2u; ++j) nvcuda::wmma::mma_sync(v4[i][j], fa[i], fb[j], v4[i][j]);
            }
        }
    }
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 2u; ++j) nvcuda::wmma::store_matrix_sync(&p4_y[(uint)(0 + 128 * gid) * 128u + (uint)(0 + 128 * gid2) * 1u + (((tid / 128u) * 64u + i * 16u) * 128u + (tid / 32u % 4u) * 32u + j * 16u)], v4[i][j], 128u, nvcuda::wmma::mem_row_major);
}
