// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : gemm_fp4_256_128_128_64_128_32
// target : apple-m-series
// launch : 4 threadgroups x 256 threads
// tg mem : 12288 B tiles + 0 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

#include <metal_simdgroup_matrix>

constant float FP4_V[16] = {
    0.0f, 0.5f, 1.0f, 1.5f, 2.0f, 3.0f, 4.0f, 6.0f,
    -0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f};
inline float2 fp4_pair(uint b) {
    const uint w = b | (b << 12u);
    return float2(as_type<half2>(((w & 0x00070007u) << 9u)
                               | ((w & 0x00080008u) << 12u)));
}
inline float fp8_e4m3(uint b) {
    const uint e = (b >> 3u) & 0xFu, m = b & 7u;
    const uint bits = select(((e + 120u) << 23u) | (m << 20u),
                             as_type<uint>(float(m) * 0.001953125f), e == 0u);
    return as_type<float>(bits | ((b & 0x80u) << 24u));
}

kernel void gemm_fp4_256_128_128_64_128_32(
    device const half* p0_x [[buffer(0)]],
    device const char* p1_wq [[buffer(1)]],
    device const char* p2_ws [[buffer(2)]],
    device const float* p3_wg [[buffer(3)]],
    device float* p4_y [[buffer(4)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x, gid2 = tgpos.y;
    threadgroup float4 arena4[768];
    threadgroup uchar* arena = (threadgroup uchar*)arena4;
    simdgroup_matrix<float, 8, 8> v2[4][4];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) v2[i][j] = simdgroup_matrix<float, 8, 8>(0.0f);
    simdgroup_matrix<float, 8, 8> v4[4][4];
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) v4[i][j] = v2[i][j];
    for (uint v3 = 0u; v3 < 4u; ++v3) {
        threadgroup half* v5 = (threadgroup half*)(arena + 0);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = tid; e < 512u; e += 256u) {
            const uint r = e / 8u, c = (e % 8u) * 4u;
            *(threadgroup half4*)(&v5[r * 32u + c]) = *(const device half4 *)(&p0_x[((uint)(0 + 64 * gid) + (((r * 32u + c)) / 32u % 64u)) * 128u + ((uint)(0 + 32 * v3) + (((r * 32u + c)) / 1u % 32u)) * 1u]);
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        threadgroup half* v10 = (threadgroup half*)(arena + 4096);
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint gi = tid; gi < 256u; gi += 256u) {
            const uint rr = gi / 2u, c0 = (gi % 2u) * 16u;
            const float sc = fp8_e4m3((uint)(uchar)(char(p2_ws[((uint)(0 + 128 * gid2) + (((gi)) / 2u % 128u)) * 8u + ((uint)(0 + 2 * v3) + (((gi)) / 1u % 2u)) * 1u])) & 0xFFu) * float(p3_wg[(uint)(0 + 128 * gid2) * 1u + ((rr))]) * 16384.0f;
            const uint2 w = *(const device uint2 *)(&p1_wq[((uint)(0 + 128 * gid2) + (((rr * 16u + c0 / 2u)) / 16u % 128u)) * 64u + ((uint)(0 + 16 * v3) + (((rr * 16u + c0 / 2u)) / 1u % 16u)) * 1u]);
            threadgroup half4* row = (threadgroup half4*)(&v10[rr * 32u + c0]);
            for (uint b = 0; b < 4u; ++b) {
                const uint wv = (b < 2u ? w.x : w.y) >> ((b & 1u) * 16u);
                const float2 lo = fp4_pair(wv & 0xFFu), hi = fp4_pair((wv >> 8u) & 0xFFu);
                row[b] = half4(half(lo.x * sc), half(lo.y * sc), half(hi.x * sc), half(hi.y * sc));
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            simdgroup_matrix<half, 8, 8> fa[4], fb[4];
            for (uint kk = 0; kk < 32u; kk += 8u) {
                for (uint i = 0; i < 4u; ++i) simdgroup_load(fa[i], v5 + ((tid / 128u) * 32u + i * 8u) * 32u + kk, 32u);
                for (uint j = 0; j < 4u; ++j) simdgroup_load(fb[j], v10 + ((tid / 32u % 4u) * 32u + j * 8u) * 32u + kk, 32u, ulong2(0, 0), true);
                for (uint i = 0; i < 4u; ++i)
                    for (uint j = 0; j < 4u; ++j) simdgroup_multiply_accumulate(v4[i][j], fa[i], fb[j], v4[i][j]);
            }
        }
    }
    for (uint i = 0; i < 4u; ++i) for (uint j = 0; j < 4u; ++j) simdgroup_store(v4[i][j], &p4_y[(uint)(0 + 64 * gid) * 128u + (uint)(0 + 128 * gid2) * 1u + (((tid / 128u) * 32u + i * 8u) * 128u + (tid / 32u % 4u) * 32u + j * 8u)], 128u);
}
