// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_300_64
// target : nvidia-ada
// launch : 1 threadgroups x 128 threads
// tg mem : 0 B tiles + 0 B scratch of 101376 B

#include <cuda_fp16.h>

typedef unsigned int uint;
typedef unsigned char uchar;
#ifndef INFINITY
#define INFINITY __int_as_float(0x7f800000)
#endif

extern "C" __global__ void matvec_300_64(
    const float* __restrict__ p0_x,
    const float* __restrict__ p1_w,
    float* __restrict__ p2_y
)
{
    const uint tid = threadIdx.x;
    const uint gid = blockIdx.x;
    float v2[3];
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            const uint i = e / 300u, j = e % 300u;
            float s = 0.0f;
            for (uint p = 0; p < 64u; ++p) s += float(float(p0_x[(uint)(0) * 64u + (uint)(0) * 1u + ((i * 64u + p))])) * float(float(p1_w[(uint)(0) * 64u + (uint)(0) * 1u + ((j * 64u + p))]));
            v2[k] = float(s);
        }
    }
    for (uint k = 0; k < 3u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 300u) {
            p2_y[(uint)(0) * 300u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
