// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : matvec_300_64
// target : apple-m-series
// launch : 1 threadgroups x 256 threads
// tg mem : 0 B tiles + 0 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void matvec_300_64(
    device const float* p0_x [[buffer(0)]],
    device const float* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x;
    float v2[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            const uint i = e / 300u, j = e % 300u;
            float s = 0.0f;
            for (uint p = 0; p < 64u; ++p) s += float(float(p0_x[(uint)(0) * 64u + (uint)(0) * 1u + ((i * 64u + p))])) * float(float(p1_w[(uint)(0) * 64u + (uint)(0) * 1u + ((j * 64u + p))]));
            v2[k] = float(s);
        }
    }
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 256u + tid;
        if (e < 300u) {
            p2_y[(uint)(0) * 300u + (uint)(0) * 1u + (e)] = float(float(v2[k]));
        }
    }
}
