// Generated by lex-msl from a lex-front program. Do not edit by hand.
// kernel : gemm_64_32_64_16_16_32
// target : apple-m-series
// launch : 4 threadgroups x 128 threads
// tg mem : 0 B tiles + 1024 B scratch of 32768 B

#include <metal_stdlib>
using namespace metal;

kernel void gemm_64_32_64_16_16_32(
    device const half* p0_a [[buffer(0)]],
    device const half* p1_w [[buffer(1)]],
    device float* p2_y [[buffer(2)]],
    uint tid [[thread_index_in_threadgroup]],
    uint3 tgpos [[threadgroup_position_in_grid]])
{
    const uint gid = tgpos.x, gid2 = tgpos.y;
    threadgroup float scratch[256];
    float v2[2];
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            v2[k] = float(0.0f);
        }
    }
    float v4[2];
    for (uint k = 0; k < 2u; ++k) v4[k] = v2[k];
    for (uint v3 = 0u; v3 < 2u; ++v3) {
        threadgroup_barrier(mem_flags::mem_threadgroup);
        {
            const uint sgid = tid / 32u, lane = tid % 32u;
            float s[4][16];
            s[0][0] = 0.0f; s[0][1] = 0.0f; s[0][2] = 0.0f; s[0][3] = 0.0f; s[0][4] = 0.0f; s[0][5] = 0.0f; s[0][6] = 0.0f; s[0][7] = 0.0f; s[0][8] = 0.0f; s[0][9] = 0.0f; s[0][10] = 0.0f; s[0][11] = 0.0f; s[0][12] = 0.0f; s[0][13] = 0.0f; s[0][14] = 0.0f; s[0][15] = 0.0f;
            s[1][0] = 0.0f; s[1][1] = 0.0f; s[1][2] = 0.0f; s[1][3] = 0.0f; s[1][4] = 0.0f; s[1][5] = 0.0f; s[1][6] = 0.0f; s[1][7] = 0.0f; s[1][8] = 0.0f; s[1][9] = 0.0f; s[1][10] = 0.0f; s[1][11] = 0.0f; s[1][12] = 0.0f; s[1][13] = 0.0f; s[1][14] = 0.0f; s[1][15] = 0.0f;
            s[2][0] = 0.0f; s[2][1] = 0.0f; s[2][2] = 0.0f; s[2][3] = 0.0f; s[2][4] = 0.0f; s[2][5] = 0.0f; s[2][6] = 0.0f; s[2][7] = 0.0f; s[2][8] = 0.0f; s[2][9] = 0.0f; s[2][10] = 0.0f; s[2][11] = 0.0f; s[2][12] = 0.0f; s[2][13] = 0.0f; s[2][14] = 0.0f; s[2][15] = 0.0f;
            s[3][0] = 0.0f; s[3][1] = 0.0f; s[3][2] = 0.0f; s[3][3] = 0.0f; s[3][4] = 0.0f; s[3][5] = 0.0f; s[3][6] = 0.0f; s[3][7] = 0.0f; s[3][8] = 0.0f; s[3][9] = 0.0f; s[3][10] = 0.0f; s[3][11] = 0.0f; s[3][12] = 0.0f; s[3][13] = 0.0f; s[3][14] = 0.0f; s[3][15] = 0.0f;
            for (uint p0 = lane * 1u; p0 < 32u; p0 += 32u) {
                for (uint u = 0; u < 1u; u += 1u) {
                    const uint p = p0 + u;
                    float xa[16][1];
                    xa[0][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 0u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 0u)) / 1u % 32u)) * 1u]));
                    xa[1][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 32u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 32u)) / 1u % 32u)) * 1u]));
                    xa[2][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 64u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 64u)) / 1u % 32u)) * 1u]));
                    xa[3][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 96u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 96u)) / 1u % 32u)) * 1u]));
                    xa[4][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 128u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 128u)) / 1u % 32u)) * 1u]));
                    xa[5][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 160u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 160u)) / 1u % 32u)) * 1u]));
                    xa[6][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 192u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 192u)) / 1u % 32u)) * 1u]));
                    xa[7][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 224u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 224u)) / 1u % 32u)) * 1u]));
                    xa[8][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 256u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 256u)) / 1u % 32u)) * 1u]));
                    xa[9][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 288u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 288u)) / 1u % 32u)) * 1u]));
                    xa[10][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 320u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 320u)) / 1u % 32u)) * 1u]));
                    xa[11][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 352u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 352u)) / 1u % 32u)) * 1u]));
                    xa[12][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 384u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 384u)) / 1u % 32u)) * 1u]));
                    xa[13][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 416u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 416u)) / 1u % 32u)) * 1u]));
                    xa[14][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 448u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 448u)) / 1u % 32u)) * 1u]));
                    xa[15][0] = float(half(p0_a[((uint)(0 + 16 * gid) + (((p + 480u)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((p + 480u)) / 1u % 32u)) * 1u]));
                    {
                        const uint j = min(sgid * 4u + 0u, 15u);
                        const float w0 = float(half(p1_w[((uint)(0 + 16 * gid2) + (((j * 32u + p)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((j * 32u + p)) / 1u % 32u)) * 1u]));
                        s[0][0] += xa[0][0] * w0;
                        s[0][1] += xa[1][0] * w0;
                        s[0][2] += xa[2][0] * w0;
                        s[0][3] += xa[3][0] * w0;
                        s[0][4] += xa[4][0] * w0;
                        s[0][5] += xa[5][0] * w0;
                        s[0][6] += xa[6][0] * w0;
                        s[0][7] += xa[7][0] * w0;
                        s[0][8] += xa[8][0] * w0;
                        s[0][9] += xa[9][0] * w0;
                        s[0][10] += xa[10][0] * w0;
                        s[0][11] += xa[11][0] * w0;
                        s[0][12] += xa[12][0] * w0;
                        s[0][13] += xa[13][0] * w0;
                        s[0][14] += xa[14][0] * w0;
                        s[0][15] += xa[15][0] * w0;
                    }
                    {
                        const uint j = min(sgid * 4u + 1u, 15u);
                        const float w0 = float(half(p1_w[((uint)(0 + 16 * gid2) + (((j * 32u + p)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((j * 32u + p)) / 1u % 32u)) * 1u]));
                        s[1][0] += xa[0][0] * w0;
                        s[1][1] += xa[1][0] * w0;
                        s[1][2] += xa[2][0] * w0;
                        s[1][3] += xa[3][0] * w0;
                        s[1][4] += xa[4][0] * w0;
                        s[1][5] += xa[5][0] * w0;
                        s[1][6] += xa[6][0] * w0;
                        s[1][7] += xa[7][0] * w0;
                        s[1][8] += xa[8][0] * w0;
                        s[1][9] += xa[9][0] * w0;
                        s[1][10] += xa[10][0] * w0;
                        s[1][11] += xa[11][0] * w0;
                        s[1][12] += xa[12][0] * w0;
                        s[1][13] += xa[13][0] * w0;
                        s[1][14] += xa[14][0] * w0;
                        s[1][15] += xa[15][0] * w0;
                    }
                    {
                        const uint j = min(sgid * 4u + 2u, 15u);
                        const float w0 = float(half(p1_w[((uint)(0 + 16 * gid2) + (((j * 32u + p)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((j * 32u + p)) / 1u % 32u)) * 1u]));
                        s[2][0] += xa[0][0] * w0;
                        s[2][1] += xa[1][0] * w0;
                        s[2][2] += xa[2][0] * w0;
                        s[2][3] += xa[3][0] * w0;
                        s[2][4] += xa[4][0] * w0;
                        s[2][5] += xa[5][0] * w0;
                        s[2][6] += xa[6][0] * w0;
                        s[2][7] += xa[7][0] * w0;
                        s[2][8] += xa[8][0] * w0;
                        s[2][9] += xa[9][0] * w0;
                        s[2][10] += xa[10][0] * w0;
                        s[2][11] += xa[11][0] * w0;
                        s[2][12] += xa[12][0] * w0;
                        s[2][13] += xa[13][0] * w0;
                        s[2][14] += xa[14][0] * w0;
                        s[2][15] += xa[15][0] * w0;
                    }
                    {
                        const uint j = min(sgid * 4u + 3u, 15u);
                        const float w0 = float(half(p1_w[((uint)(0 + 16 * gid2) + (((j * 32u + p)) / 32u % 16u)) * 64u + ((uint)(0 + 32 * v3) + (((j * 32u + p)) / 1u % 32u)) * 1u]));
                        s[3][0] += xa[0][0] * w0;
                        s[3][1] += xa[1][0] * w0;
                        s[3][2] += xa[2][0] * w0;
                        s[3][3] += xa[3][0] * w0;
                        s[3][4] += xa[4][0] * w0;
                        s[3][5] += xa[5][0] * w0;
                        s[3][6] += xa[6][0] * w0;
                        s[3][7] += xa[7][0] * w0;
                        s[3][8] += xa[8][0] * w0;
                        s[3][9] += xa[9][0] * w0;
                        s[3][10] += xa[10][0] * w0;
                        s[3][11] += xa[11][0] * w0;
                        s[3][12] += xa[12][0] * w0;
                        s[3][13] += xa[13][0] * w0;
                        s[3][14] += xa[14][0] * w0;
                        s[3][15] += xa[15][0] * w0;
                    }
                }
            }
            for (uint d = 16u; d > 0; d /= 2) s[0][0] += simd_shuffle_down(s[0][0], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][1] += simd_shuffle_down(s[0][1], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][2] += simd_shuffle_down(s[0][2], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][3] += simd_shuffle_down(s[0][3], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][4] += simd_shuffle_down(s[0][4], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][5] += simd_shuffle_down(s[0][5], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][6] += simd_shuffle_down(s[0][6], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][7] += simd_shuffle_down(s[0][7], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][8] += simd_shuffle_down(s[0][8], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][9] += simd_shuffle_down(s[0][9], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][10] += simd_shuffle_down(s[0][10], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][11] += simd_shuffle_down(s[0][11], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][12] += simd_shuffle_down(s[0][12], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][13] += simd_shuffle_down(s[0][13], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][14] += simd_shuffle_down(s[0][14], d);
            for (uint d = 16u; d > 0; d /= 2) s[0][15] += simd_shuffle_down(s[0][15], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][0] += simd_shuffle_down(s[1][0], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][1] += simd_shuffle_down(s[1][1], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][2] += simd_shuffle_down(s[1][2], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][3] += simd_shuffle_down(s[1][3], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][4] += simd_shuffle_down(s[1][4], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][5] += simd_shuffle_down(s[1][5], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][6] += simd_shuffle_down(s[1][6], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][7] += simd_shuffle_down(s[1][7], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][8] += simd_shuffle_down(s[1][8], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][9] += simd_shuffle_down(s[1][9], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][10] += simd_shuffle_down(s[1][10], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][11] += simd_shuffle_down(s[1][11], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][12] += simd_shuffle_down(s[1][12], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][13] += simd_shuffle_down(s[1][13], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][14] += simd_shuffle_down(s[1][14], d);
            for (uint d = 16u; d > 0; d /= 2) s[1][15] += simd_shuffle_down(s[1][15], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][0] += simd_shuffle_down(s[2][0], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][1] += simd_shuffle_down(s[2][1], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][2] += simd_shuffle_down(s[2][2], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][3] += simd_shuffle_down(s[2][3], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][4] += simd_shuffle_down(s[2][4], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][5] += simd_shuffle_down(s[2][5], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][6] += simd_shuffle_down(s[2][6], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][7] += simd_shuffle_down(s[2][7], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][8] += simd_shuffle_down(s[2][8], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][9] += simd_shuffle_down(s[2][9], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][10] += simd_shuffle_down(s[2][10], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][11] += simd_shuffle_down(s[2][11], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][12] += simd_shuffle_down(s[2][12], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][13] += simd_shuffle_down(s[2][13], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][14] += simd_shuffle_down(s[2][14], d);
            for (uint d = 16u; d > 0; d /= 2) s[2][15] += simd_shuffle_down(s[2][15], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][0] += simd_shuffle_down(s[3][0], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][1] += simd_shuffle_down(s[3][1], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][2] += simd_shuffle_down(s[3][2], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][3] += simd_shuffle_down(s[3][3], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][4] += simd_shuffle_down(s[3][4], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][5] += simd_shuffle_down(s[3][5], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][6] += simd_shuffle_down(s[3][6], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][7] += simd_shuffle_down(s[3][7], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][8] += simd_shuffle_down(s[3][8], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][9] += simd_shuffle_down(s[3][9], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][10] += simd_shuffle_down(s[3][10], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][11] += simd_shuffle_down(s[3][11], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][12] += simd_shuffle_down(s[3][12], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][13] += simd_shuffle_down(s[3][13], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][14] += simd_shuffle_down(s[3][14], d);
            for (uint d = 16u; d > 0; d /= 2) s[3][15] += simd_shuffle_down(s[3][15], d);
            if (lane == 0) {
                { const uint j = sgid * 4u + 0u; if (j < 16u) { scratch[0 + 0u + j] = s[0][0]; scratch[0 + 16u + j] = s[0][1]; scratch[0 + 32u + j] = s[0][2]; scratch[0 + 48u + j] = s[0][3]; scratch[0 + 64u + j] = s[0][4]; scratch[0 + 80u + j] = s[0][5]; scratch[0 + 96u + j] = s[0][6]; scratch[0 + 112u + j] = s[0][7]; scratch[0 + 128u + j] = s[0][8]; scratch[0 + 144u + j] = s[0][9]; scratch[0 + 160u + j] = s[0][10]; scratch[0 + 176u + j] = s[0][11]; scratch[0 + 192u + j] = s[0][12]; scratch[0 + 208u + j] = s[0][13]; scratch[0 + 224u + j] = s[0][14]; scratch[0 + 240u + j] = s[0][15]; } }
                { const uint j = sgid * 4u + 1u; if (j < 16u) { scratch[0 + 0u + j] = s[1][0]; scratch[0 + 16u + j] = s[1][1]; scratch[0 + 32u + j] = s[1][2]; scratch[0 + 48u + j] = s[1][3]; scratch[0 + 64u + j] = s[1][4]; scratch[0 + 80u + j] = s[1][5]; scratch[0 + 96u + j] = s[1][6]; scratch[0 + 112u + j] = s[1][7]; scratch[0 + 128u + j] = s[1][8]; scratch[0 + 144u + j] = s[1][9]; scratch[0 + 160u + j] = s[1][10]; scratch[0 + 176u + j] = s[1][11]; scratch[0 + 192u + j] = s[1][12]; scratch[0 + 208u + j] = s[1][13]; scratch[0 + 224u + j] = s[1][14]; scratch[0 + 240u + j] = s[1][15]; } }
                { const uint j = sgid * 4u + 2u; if (j < 16u) { scratch[0 + 0u + j] = s[2][0]; scratch[0 + 16u + j] = s[2][1]; scratch[0 + 32u + j] = s[2][2]; scratch[0 + 48u + j] = s[2][3]; scratch[0 + 64u + j] = s[2][4]; scratch[0 + 80u + j] = s[2][5]; scratch[0 + 96u + j] = s[2][6]; scratch[0 + 112u + j] = s[2][7]; scratch[0 + 128u + j] = s[2][8]; scratch[0 + 144u + j] = s[2][9]; scratch[0 + 160u + j] = s[2][10]; scratch[0 + 176u + j] = s[2][11]; scratch[0 + 192u + j] = s[2][12]; scratch[0 + 208u + j] = s[2][13]; scratch[0 + 224u + j] = s[2][14]; scratch[0 + 240u + j] = s[2][15]; } }
                { const uint j = sgid * 4u + 3u; if (j < 16u) { scratch[0 + 0u + j] = s[3][0]; scratch[0 + 16u + j] = s[3][1]; scratch[0 + 32u + j] = s[3][2]; scratch[0 + 48u + j] = s[3][3]; scratch[0 + 64u + j] = s[3][4]; scratch[0 + 80u + j] = s[3][5]; scratch[0 + 96u + j] = s[3][6]; scratch[0 + 112u + j] = s[3][7]; scratch[0 + 128u + j] = s[3][8]; scratch[0 + 144u + j] = s[3][9]; scratch[0 + 160u + j] = s[3][10]; scratch[0 + 176u + j] = s[3][11]; scratch[0 + 192u + j] = s[3][12]; scratch[0 + 208u + j] = s[3][13]; scratch[0 + 224u + j] = s[3][14]; scratch[0 + 240u + j] = s[3][15]; } }
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float v7[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                v7[k] = float(scratch[0 + e]);
            }
        }
        float v8[2];
        for (uint k = 0; k < 2u; ++k) {
            const uint e = k * 128u + tid;
            if (e < 256u) {
                v8[k] = float(float(v4[k]) + float(v7[k]));
            }
        }
        for (uint k = 0; k < 2u; ++k) v4[k] = v8[k];
    }
    for (uint k = 0; k < 2u; ++k) {
        const uint e = k * 128u + tid;
        if (e < 256u) {
            p2_y[((uint)(0 + 16 * gid) + ((e) / 16u % 16u)) * 32u + ((uint)(0 + 16 * gid2) + ((e) / 1u % 16u)) * 1u] = float(float(v4[k]));
        }
    }
}
